Cargo.toml, objects/Cargo.toml, objects/README.md, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/errors.rs, objects/src/lib.rs, rustfmt.toml
This PR implements the `AccountId` struct which describes the shape and properties of all account Ids in the Miden rollup.
The PR also sets up the basic crate structure for the repo.
=> Implement AccountId object

objects/Cargo.toml, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/notes/mod.rs, objects/src/notes/script.rs, objects/src/notes/vault.rs
This PR implements basic parts of the `Note` object. This is not yet a full implementation. Specifically:
- Serialization/deserialization of notes is note implemented.
- `NoteScript` struct is only sketched out. There are some open questions on how exactly we should compile source into programs here.
- Partial representation of notes is not provided.
Also, this PR includes a fix for a small bug in the `assets` module found by @Al-Kindi-0 .
=> Implement Note object

objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage.rs, objects/src/accounts/vault.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs
This PR defines basic structure of the account object. This does not yet include the idea of changing account IDs to 64-bit values. Other things missing:
- Since we don't have an implementation of compact Sparse Merkle tree, account vault and storage have TODOs in their place.
- Account code does actually get compiled into MAST yet. For this, we need to make changes to the assembler to enable compilation of modules into multi-entry programs.
- Serialization of account object is not implemented.
There are some open questions about how to compile program code while also including user-defined libraries. We probably don't need this for the testnet, but if there are some good ways of doing this, we could address it even now.
=> Define basic account object

objects/src/errors.rs, objects/src/notes/inputs.rs, objects/src/notes/mod.rs
This PR introduces note script inputs.  It also updates the way note commitments and nullifies are computed.  
Note Commitment modification:
- An additional 2-1 hash is added as the last step to the hash chain  which involves a hash with the script inputs hash.
Nulifier Modification:
- Introduction of script inputs hash as the third word in the nulifier linear hash. 
- Padding removed as with the introduction of script inputs hash we now have 16 elements to be hashed.
Is there any interesting structure in: 
`Hasher::merge(&[script.hash(), script_inputs.hash()]);`
If we assume that the script is for receiving assets from the note vault and the script input is the account_id of the recipient this would be unique for every user for each wallet type.
closes: #9
=> feat(objects): introduce note script inputs

.github/workflows/ci.yml, objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/accounts/vault.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/utils.rs
This PR introduces github ci workflow which is copied from the `miden-vm` repo.  We also introduce a `utils` module in which we specify imports for `std` / `no_std` environments;
=> Introduce github CI + `no_std` compatibility 

objects/Cargo.toml, objects/benches/account_seed.rs, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/accounts/tests.rs, objects/src/accounts/vault.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs
This PR migrates from 24 byte AccountId to 64 bits (a single field element). It introduces additional modifications to non-fungible assets suggested in #8.
=> feat(objects): migrate to ~64 bit AccountId

objects/src/lib.rs, objects/src/transaction/compiled_tx.rs, objects/src/transaction/mod.rs
This PR implements the `CompiledTransaction` object.
closes: #45
=> Implement CompiledTransaction

.git-blame-ignore-revs
the pre-commit PR has been merged, this adds the commit that ran pre-commit and formated the code base into the [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file)
=> chore: ignore pre-commit rev

miden-lib/asm/sat/epilogue.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/prologue.masm, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/procedures.rs, miden-lib/tests/test_prologue.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/transaction/created_note.rs, objects/src/transaction/mod.rs, objects/src/transaction/proven_tx.rs, objects/src/transaction/utils.rs
This PR introduces a rust struct `NoteMetadata` that is used to represent note metadata.  This struct is structured as follows:
```rust
pub struct NoteMetadata {
sender: AccountId,
tag: Felt,
num_assets: Felt,
}
```
We modify kernel memory layout to remove the row that previously existed for `*_NUM_ASSETS` for created and consumed notes and instead use the `num_assets` field from metadata.
This PR also introduces some additional getters and setters to improve the readability of the prologue.
=> Introduce NoteMetadata struct and refactor memory layout

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/epilogue.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/tx.masm, miden-lib/tests/test_epilogue.rs
This is an initial draft for the kernel procedures.  We currently support:
- `miden::sat::account::get_id`
- `miden::sat::account::get_nonce`
- `miden::sat::account::get_initial_hash`
- `miden::sat::account::get_current_hash`
- `miden::sat::account::incr_nonce`
- `miden::sat::tx::get_input_notes_hash`
- `miden::sat::tx::get_output_notes_hash`
The remaining procedures have dependencies on the SMT and vault implementation.
=> Introduce kernel procedures

miden-lib/Cargo.toml, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/prologue.masm, miden-lib/asm/sat/tx.masm, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_prologue.rs, objects/src/block/header.rs, objects/src/block/mod.rs, objects/src/lib.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/inputs.rs, objects/src/transaction/mod.rs, objects/src/transaction/utils.rs
This PR introduces the block header object which holds metadata that succinctly describes the current state of the chain and provides commitments that can be used to authenticate historical and current state. A rust struct has been implemented to encapsulate logic and data related to the block header.  We have also extended the prologue to parse and authenticate block data which is provided via the advice provider and authenticate that it is consistent with the block hash provided via public input.
=> Introduce block header object

miden-lib/Cargo.toml, miden-lib/asm/sat/constants.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/prologue.masm, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_note_setup.rs, miden-lib/tests/test_prologue.rs, objects/Cargo.toml, objects/src/block/header.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/inputs.rs, objects/src/transaction/mod.rs, objects/src/transaction/utils.rs
This is functional draft PR for note authentication.  This is a work in progress and some refactoring is required and additional documentation will be supplemented. This PR introduces a `NoteOrigin` struct which is responsible for holding the information related to the origin of a note - specifically the block header of the block it was created in and in the index of the note in the note tree for that block.  We modify note Felt serialization to include origin information such that the masm code can authenticate the notes origin. We modify the testing patterns such that we can include a `MerkleStore` when constructing the advice provider.
=> Note authentication draft

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/epilogue.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/prologue.masm, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_prologue.rs
This PR introduces the `set_code` procedure.  We also introduce a `type` procedure which returns the type of the account.  We should consider if we want to expose this publicly or keep it private?
=> Add `set_code` kernel procedure

miden-lib/asm/sat/account.masm, miden-lib/tests/common/mod.rs, miden-lib/tests/test_account.rs
This PR implements four procedures to provide insight regarding the type of account the transaction is being executed against:
- is_fungible_faucet
- is_non_fungible_faucet
- is_updatable_account
- is_immutable_account
=> Add account type procedures

miden-lib/asm/sat/note.masm, miden-lib/asm/sat/note_setup.masm, miden-lib/tests/test_note.rs, miden-lib/tests/test_note_setup.rs, objects/src/notes/mod.rs, objects/src/notes/vault.rs, objects/src/transaction/utils.rs
This PR introduces the `get_assets` procedure and the `get_vault_data` procedure it depends on. We also modify `get_sender` procedure to panic when it is called from an incorrect context (e.g. tx script) such that it is consistent with other note procedures.
=> Add get assets procedure

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/layout.masm, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_prologue.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage.rs, objects/src/errors.rs, objects/src/lib.rs
This PR changes `AccountStorage` such that it is implemented as described in #92.  We introduce storage procedures to get and set account storage items.
=> Add storage procedures

miden-lib/Cargo.toml, miden-lib/asm/sat/note_setup.masm, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_note.rs, miden-lib/tests/test_note_setup.rs, miden-lib/tests/test_prologue.rs, objects/Cargo.toml, objects/src/accounts/mod.rs, objects/src/advice.rs, objects/src/block/header.rs, objects/src/block/mod.rs, objects/src/chain/mod.rs, objects/src/lib.rs, objects/src/notes/mod.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/inputs.rs, objects/src/transaction/mod.rs, objects/src/transaction/utils.rs
- Introduces `AdviceProviderBuilder` and `ToAdviceInputs` traits.  
- Implements `AdviceProviderBuilder` on `AdviceInputs` and `ToAdviceInputs` on the types that we need to load into the advice provider for transaction execution.
- Modifies the note setup script to source note inputs from the advice map.
- Introduces a `ChainMmr` object which wrap the `Mmr` object to support chain mmr data.
Open question: do we want to introduce the `ChainMmr` struct or should we just implement `ToAdviceInputs` on `Mmr` directly.
=> Introduce `AdviceProviderBuilder` and `ToAdviceInputs` traits

miden-lib/build.rs
This PR fixes `miden-base` by updating the `MaslLibrary::read_from_dir(..)` invocation to align with the new interface. Specifically, we set `with_source_locations = false`.
=> Fix Masl build

docs/book.toml
output.katex doesn't work anymore and needs to be removed from book.toml
https://github.com/lzanini/mdbook-katex/issues/68
=> docs: mdbook fix book.toml

docs/src/network.md
For some reason, the miden docs are not shown anymore. 
https://0xpolygonmiden.github.io/miden-base/introduction.html
There were updates in `mdbook` and `mdbook-katex` so in the `book.toml` we had to remove `[output.katex]`
=> docs: html doesn't get rendered [WIP - testing]

miden-lib/Cargo.toml, miden-lib/asm/sat/account.masm, miden-lib/asm/sat/epilogue.masm, miden-lib/asm/sat/note_setup.masm, miden-lib/asm/sat/prologue.masm, objects/Cargo.toml
Refactor to support updated `mem_stream` and `adv_pipe` operations. We should do a more comprehensive analysis to see if we can leverage the updated operations to achieve some performance improvements but this is out of scope for now.  I have created an issue to follow up on this #135.
=> Support updated mem_stream and adv_pipe operations

miden-lib/asm/sat/account_vault.masm, miden-lib/asm/sat/asset.masm, miden-lib/asm/sat/layout.masm, miden-lib/src/lib.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_asset_vault.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_prologue.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/accounts/vault.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/notes/script.rs
This is a draft implementation of the `AssetVault`.
@bobbinth I don't think it makes sense to have both `Vec<Asset>` and `TieredSmt` backing the `AssetVault`.  It increase the complexity and introduces a lot of duplication.  I think we should remove it.  One implication is we wont be able to support: 
```rust
/// Returns a list of assets stored in this vault.
pub fn assets(&self) -> &[Asset] {
&self.assets
}
```
This would have to change to as seen below which requires allocations:
```rust
/// Returns a list of assets stored in this vault.
pub fn to_assets(&self) -> Iterator<Item=Asset> {
...
}
```
What do you think?
=> Implement `AssetVault`

Cargo.toml, miden-lib/Cargo.toml, miden-lib/asm/sat/kernel.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/note.masm, miden-lib/asm/sat/note_setup.masm, miden-lib/src/lib.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/mod.rs, miden-lib/tests/test_note.rs, miden-tx/Cargo.toml, miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/error.rs, miden-tx/src/lib.rs, objects/src/accounts/account_id.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/notes/inputs.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/notes/script.rs
This PR introduces the `tx-compiler` described in #141.  We also modify the note setup script to address the issues described in #143.  We introduce the `kernel` module (`kernel.masm`) which is a module that contains all kernel procedures - this currently re-exports procedures from other modules using the procedure export pattern. Additionally we introduce a rust `TransactionKernel` type which contains all `Kernel` associated data and types.  A note processing teardown program has been introduced which is run at the end of note processing to reset the current consumed note pointer to 0.
=> feat: introduce tx-compiler

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/note.masm, miden-lib/asm/sat/note_setup.masm
the advice instructions were [renamed](https://github.com/0xPolygonMiden/miden-vm/pull/933), this fixes the miden-lib code (otherwise the `build.rs` fails to run)
=> bugfix: adv.keyval -> adv.push_mapval

objects/src/transaction/mod.rs
Removing `pub(self)` as suggested by Clippy
=> fix: remove clippy warning

docs/src/architecture.md
As discussed with @bobbinth, I re-worked the architecture overview section. 
Specifically: 
- Goal is for developers to understand how Miden works
- I removed all marketing phrases, e.g., "extending the design space". 
- I removed the tx lifecycle (however, I will add it again under the transaction chapter)
- Overview entails now
- Goals (as user benefits)
- Summaries of the chapters that follow
Let me know what you think.
=> docs: new version of the architecture overview

docs/src/SUMMARY.md, docs/src/architecture/transactions.md
Review after #151, #159, #160 and #161 
As discussed with @bobbinth, I reworked the transactions section.
Specifically:
- Goal is for developers to understand how Miden works
- I removed all marketing phrases, e.g., "extending the design space".
- I added a goal on top - goal of the design is to allow parallel and private transactions
- I removed some diagrams ab transaction execution
- I rephrased some paragraphs to make it a better, more concise read
Let me know what you think.
=> docs: iterating over transactions section

miden-tx/Cargo.toml, miden-tx/src/compiler/mod.rs, miden-tx/src/error.rs, miden-tx/src/lib.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests.rs, miden-tx/src/verifier/mod.rs, objects/src/transaction/proven_tx.rs
=> Introduce `TransactionVerifier`

miden-lib/asm/sat/internal/account.masm, miden-lib/asm/sat/internal/constants.masm, miden-lib/asm/sat/internal/layout.masm, miden-lib/asm/sat/internal/prologue.masm, miden-lib/src/memory.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_asset_vault.rs, miden-lib/tests/test_note.rs, miden-lib/tests/test_note_setup.rs, miden-lib/tests/test_prologue.rs, miden-tx/src/error.rs, miden-tx/src/executor/mod.rs, miden-tx/src/tests.rs, objects/benches/account_seed.rs, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/block/header.rs, objects/src/chain/mod.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/mock.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/mod.rs, objects/src/transaction/prepared_tx.rs, objects/src/transaction/tx_result.rs, objects/src/transaction/tx_witness.rs, objects/src/transaction/utils.rs
Tests failing due to - https://github.com/0xPolygonMiden/miden-base/pull/185.  Rebasing will fix tests once merged.
Introduces account creation logic in the kernel.
We identify a new account by checking if the nonce is equal to zero. If the account is new then we enforce the condition that the nonce must be incremented in the transaction, this condition is enforced in the epilogue.  We now apply two permutations of the hashing function to compute the seed digest and as such the work has doubled.  To account for the doubling of work I have reduced the required trailing bits by one.  
closes: #87, #84
=> Introduce `create_account` kernel section

objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage.rs, objects/src/accounts/stub.rs, objects/src/accounts/vault.rs
This adds serde support for the account object.
Note: For the account code, instead of adding serde to the `miden-vm` this is using a custom serializer and encoding it as `[u8]`. I did this because I don't think users will edit the bytecode by hand, and there doesn't seem to be an API to convert the module ast to miden assembly.
=> serde: initial implementation for account objects

objects/src/accounts/account_id.rs
As the title says. This makes it easier to pass the values around (for example, from a non-consuming builder of an AccountId
=> AccountType: derive copy and clone

objects/src/notes/inputs.rs, objects/src/notes/mod.rs
There was an error check in place, but the value was not being returned. This fixes that, and also re-exports the note structures on top-level (like the rest).
I think we should start annotating error types with `#[must_use]` to caught this. Objections?
=> bugfix: note inputs didn't return error

objects/src/notes/envelope.rs, objects/src/notes/metadata.rs, objects/src/notes/stub.rs, objects/src/transaction/consumed_notes.rs, objects/src/transaction/created_notes.rs
Adds conversions for references in addition to the existing consuming conversions. This makes it easier to create a stubs and envelopes without consuming them, which is useful for testing. Also adds some other useful conversions for consumed and created notes.
=> Additional conversions for note types

miden-lib/tests/test_account.rs, miden-lib/tests/test_asset_vault.rs, miden-lib/tests/test_prologue.rs, miden-tx/src/verifier/mod.rs, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/assets/fungible.rs, objects/src/assets/nonfungible.rs, objects/src/mock/block.rs, objects/src/transaction/tx_witness.rs, objects/src/transaction/utils.rs
This is not strictly necessary, I think it is just a nice to have.
From the stdlib docs:
The idea is that `Deref` should be implemented by classes that manage resources (i.e. a smart pointer). Which is not the case for the `Felt` values we have here, these are copyable types which should fit in a register.
This PR removes the `Deref` implementation to follow the recommendation of the stdlib.
=> remove Deref impl from non smart pointers

objects/src/builder/mod.rs, objects/src/lib.rs, objects/src/notes/envelope.rs
This PR does:
- Add a builder for `Note`s
- Add a conversion from `Note` to `NoteEnvelope`
- Removed top-level re-exports (as discussed on https://github.com/0xPolygonMiden/miden-base/pull/207)
=> Add note builder

miden-lib/asm/sat/internal/asset_vault.masm, miden-lib/tests/test_asset_vault.rs
This PR makes minor modifications to the asset vault masm implementation to use the `set` procedure on the SMT for deletions. We also remove the ignore flags for tests related to vault asset deletion.
=> Integrate upstream tsmt delete for asset vault masm

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/kernel.masm, miden-lib/tests/test_account.rs
This PR introduces `account::get_vault_commitment` procedure which is the last procedure of the vault interface.
closes: #69
=> Introduce account::get_vault_commitment procedure

miden-tx/src/error.rs, objects/src/assets/fungible.rs, objects/src/errors.rs, objects/src/mock/chain.rs
delegates the formatting to the debug implementation instead of calling `todo!`. Also implements `Debug` and `std::error::Error` for the mock errors.
=> error: delegate display to debug formatting

miden-lib/asm/sat/asset.masm, miden-lib/asm/sat/faucet.masm, miden-lib/asm/sat/internal/account.masm, miden-lib/asm/sat/internal/asset.masm, miden-lib/asm/sat/internal/asset_vault.masm, miden-lib/asm/sat/internal/faucet.masm, miden-lib/asm/sat/kernel.masm, miden-lib/src/memory.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_asset.rs, miden-lib/tests/test_asset_vault.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_faucet.rs, miden-lib/tests/test_note.rs, miden-lib/tests/test_note_setup.rs, miden-lib/tests/test_prologue.rs, miden-tx/src/tests.rs, objects/src/accounts/storage.rs, objects/src/mock/account.rs, objects/src/mock/chain.rs, objects/src/mock/constants.rs, objects/src/mock/mod.rs, objects/src/mock/notes.rs, objects/src/mock/transaction.rs
This PR introduces `mint` and `burn` functionality for faucet accounts.
This PR includes the following:
- Introduction of `faucet` module consisting of `mint` and `burn` kernel procedures.
- Fix bug with `add_fungible_asset` procedure when the vault had no balance for the fungible asset being added to the vault.
- Fix bug with `remove_fungible_asset` procedure to ensure that the vault has sufficient balance for the fungible asset being removed.
- Implement reserved storage slot (255) for faucet accounts.
closes: #118
=> Introduce faucet mint and burn procedures

objects/src/mock/chain.rs
the builder was using the wrong constant
=> bugfix fungible builder

objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/accounts/seed.rs
~merge/review after #223~
This adds parallel PoW to the account id seed. Notes:
- The original code receives a single seed instead of PRNG, this doesn't change that, it just changes the seeds by adding a constant to the last element. It should be good enough since the inner loop used the RPO digest to get the next seed value.
- Parallelism is enabled by the `std` flag, since this uses the std lib to create threads and for the synchronization primitives
To visualize the logs from the threads an environment variable is needed:
```
RUST_LOG=debug cargo run
```
fixes #35
=> Parallel account id pow

objects/src/accounts/mod.rs
Adding a new `set_nonce()` method to our accounts. We need that to create a mock_chain with existing accounts.
=> feat: adding set_nonce to the Account

objects/src/accounts/storage.rs, objects/src/builder/mod.rs, objects/src/mock/chain.rs
Changes the mock chain to also keep track of the account's seed. The seed is used to test the account creation transaction.
=> mock: preserve the account's seed, required for the create transaction

miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/lib.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/lib.rs, objects/src/mock/chain.rs, objects/src/notes/mod.rs, objects/src/notes/script.rs
https://github.com/0xPolygonMiden/miden-vm/pull/1063 changed the AssemblyContext API, so main is no longer compiling. This updates the code to match the new api.
=> chore: updated code to match latest AssemblyContext API changes

objects/src/accounts/account_id.rs
Adds a paragraph documenting the final PoW for account ids.
With these `3` added bits, a faucet id requires `34` bits of work. At 200k hashes/sec the expected time should be around 23hours of CPU time.
=> docs: add note about total PoW for faucet id

miden-lib/asm/sat/internal/asset_vault.masm
This PR refactors the asset vault implementation to use `push_smtpeek` decorator which improves efficiency.
=> refactor: use push_smtpeek for asset vault

miden-lib/asm/note_scripts/basic.masm, miden-lib/src/tests/mod.rs, miden-lib/src/tests/test_note_scripts.rs
Closing https://github.com/0xPolygonMiden/miden-base/issues/12 (finally)
I created a new folder, `note_scripts`, in which I created a file, `basic.masm`. The file entails the p2id and p2idr scripts. 
Testing is quite complex. But I hope it is well documented. Basically, I had to create three different accounts, and they all tried to consume the note. In the second test, at two different points in time. 
Still left: 
- use commenting style of our other masm files
- check in the p2idr script the account state after the transaction
=> Adding p2id and p2idr scripts and tests

miden-lib/asm/sat/faucet.masm, miden-lib/asm/sat/internal/faucet.masm, miden-lib/asm/sat/kernel.masm, miden-lib/src/tests/test_faucet.rs
This PR implements the `faucet::get_total_issuance` procedure which allows the user to query the total issuance of the fungible faucet the transaction is being executed against.
Procedure description:
```
#! Returns the total issuance of the fungible faucet the transaction is being executed against.
#!
#! Panics:
#! - If the transaction is not being executed against a fungible faucet.
#!
#! Stack: []
#! Outputs: [total_issuance]
#!
#! - total_issuance is the total issuance of the fungible faucet the transaction is being executed
#!   against.
```
closes: #260
=> Implement `faucet::get_total_issuance` procedure

miden-lib/src/notes/mod.rs, miden-lib/src/tests/mod.rs, miden-tx/tests/test_miden_note_scripts.rs, objects/src/lib.rs
Closes #259 
This is based on #263 because I use the same integration testing structure. 
I moved `test_note_scripts` to `miden-tx` to test it the same way as the faucet smart contract and the wallet.
I added a `Script` Structure and a `create_note_with_script` in `miden-lib/src/notes/mod.rs`. That seemed to be the best place.
=> Set up structure for standard note scripts

miden-lib/src/lib.rs, miden-lib/src/wallets/mod.rs, miden-tx/tests/test_miden_wallet.rs, objects/src/lib.rs
Closes #272 
Note: 
- I can't use this scheme in the integration tests in `miden-tx/tests/test-miden-wallet.rs` because in those tests I need accounts with a nonce > 1
- I will use the `AuthScheme` later, when the `Falcon` key implementation is ready
- After https://github.com/0xPolygonMiden/miden-vm/issues/1098 is closed, we can move the MASM code into a file
=> feat: adding a basic wallet creation scheme

miden-lib/asm/faucets/basic.masm, miden-lib/src/auth.rs, miden-lib/src/faucets/mod.rs, miden-lib/src/lib.rs, miden-lib/src/wallets/mod.rs, miden-tx/tests/test_miden_faucet_contract.rs, miden-tx/tests/test_miden_wallet.rs, objects/src/assets/mod.rs, objects/src/assets/token_symbol.rs, objects/src/errors.rs
Adds a new method to `miden-lib` to create a basic faucet account. The user can provide 
- the authentication scheme
- the metadata:
- max supply
- token decimals
- token symbol
I added an integration test in `miden-tx` in `test_miden_faucet_contract`. 
_Note: the other integration tests in that file need to use a different create_faucet function because we need to create an existing faucet, i.e., a faucet with Nonce >0, for tests._
=> feat: adds method for quick faucet creation

miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/executor/mod.rs, miden-tx/src/lib.rs, miden-tx/src/verifier/mod.rs
Fixes typo in `TransactionCompiler`, and removes the duplication of the struct with `#[cfg(test/not(test))]`.
Specifically, the `#[cfg(not(test))]` on a core struct confused rust-analyzer, and I couldn't lookup symbols in the `impl` block.
=> Nit: Rename `TransactionCompiler`

miden-lib/asm/sat/internal/epilogue.masm, miden-lib/src/tests/test_tx.rs
This PR refactors the epilogue to extract the logic for building the output vault into a separate procedure.  This should fix the issue described in #295.
closes: #295
=> refactor: Move build output vault logic to a separate procedure

miden-lib/src/notes/mod.rs, miden-lib/src/tests/test_note.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/tests/test_tx.rs, miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/data.rs, miden-tx/src/lib.rs, miden-tx/src/tests.rs, miden-tx/tests/common/mod.rs, miden-tx/tests/test_miden_faucet_contract.rs, miden-tx/tests/test_miden_note_scripts.rs, miden-tx/tests/test_miden_wallet.rs, mock/src/builders/note.rs, mock/src/lib.rs, mock/src/mock/chain.rs, mock/src/mock/notes.rs, mock/src/mock/transaction.rs, objects/src/notes/mod.rs, objects/src/transaction/consumed_notes.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/mod.rs, objects/src/transaction/prepared_tx.rs, objects/src/transaction/utils.rs
This PR introduces the a `RecordedNote` object which represents a `Note` which has been been included in the miden notes database. This addresses the points raised in #113. It is structured as follows:
```rust
pub struct RecordedNote {
note: Note,
proof: NoteInclusionProof,
}
```
This eliminates the need to have an optional `NoteInclusionProof` in the `Note` struct which then has to be unwrapped in the advice inputs builder logic.  Some changes were required to the `mock` crate.  I would appreciate a review of these changes from @hackaugusto who is most familiar with it.
closes: #113
=> Introduce `RecordedNote` object

miden-lib/asm/sat/internal/layout.masm, miden-lib/asm/sat/internal/main.masm, miden-lib/asm/sat/internal/note.masm, miden-lib/asm/sat/internal/prologue.masm, miden-lib/src/memory.rs, miden-lib/src/tests/test_note.rs
This PR refactors the kernel booking layout as described in #287 and #280. Specifically we remove `CURRENT_CONSUMED_NOTE_IDX` and `NUM_EXECUTED_NOTES_PTR`.  To support this change we have modified the looping login in `main.masm` such that the termination condition is when the current consumed note pointer matches the calculated loop termination pointer.  We initialise the current consumed note pointer in the prologue.
closes: #287, #280
=> refactor: refactor kernel book keeping memory layout and management

mock/src/mock/mmr_peaks.rs, mock/src/mock/mod.rs
Adds a mock function to create an empty `MmrPeaks`.
Outcome of discussion: https://github.com/0xPolygonMiden/crypto/pull/218
=> Add mock function `empty_mmr_peaks()`

miden-lib/src/tests/test_prologue.rs, mock/src/constants.rs, mock/src/mock/account.rs
This PR introduces generation of account seeds and id's at runtime.  This addresses #304. We should do something similar for #303.
closes: #304
=> Generate test account seeds at runtime

objects/src/notes/envelope.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/notes/script.rs
This PR introduces a `from_parts` constructor for the `Note` object.
=> Introduce `from_parts` constructor for Note object

_config.yml, docs/src/architecture.md
The cool new gif that captures the gist of Miden can not be rendered with the GitHubPages standard renderer. 
The problem here is that Markdown on GitHub.com is rendered with our [CommonMark-compatible renderer](https://blog.github.com/2017-03-14-a-formal-spec-for-github-flavored-markdown/), but Pages by default uses kramdown. See here https://github.com/github/markup/issues/1215
=> docs: fix gif

objects/src/lib.rs
Expose `ToAdviceInputs` for use in `miden-node` and others
=> Expose `ToAdviceInputs`

objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/errors.rs, objects/src/lib.rs
This PR fixes/cleans-up a few things in the `AccountCode` struct. Specifically:
- Replaces binary search with linear search in `has_procedure()` and `get_procedure_index_by_root()`. Using binary search here could lead to wrong results as of [#320](https://github.com/0xPolygonMiden/miden-base/pull/320).
- Fixes serialization: previously source locations were not serialized and thus, deserialized structs would not be equal to their original. Separately, we may want to refactor serialization of source locations in `ModuleAst` (to be controlled via `AstSerdeOptions`).
- Puts `procedure_tree` behind `OneCell` so that we build it only when we need it.
- Removes `unsafe` modifier from the `from_parts()` constructor as the un-checked properties there are not really about memory safety.
=> `AccountCode` cleanup

Cargo.toml, objects/src/accounts/account_id.rs, objects/src/assets/mod.rs, objects/src/notes/envelope.rs, objects/src/notes/inputs.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/notes/script.rs, objects/src/notes/vault.rs, objects/src/transaction/consumed_notes.rs, objects/src/transaction/proven_tx.rs
as per the pr title.
fixes: #6
=> serde: implementation for proven transaction

miden-tx/src/lib.rs, miden-tx/src/prover/mod.rs, objects/src/transaction/executed_tx.rs
Needed to utilize the prover correctly from the client.
=> Re-export `ProvingOptions`

objects/src/transaction/mod.rs, objects/src/transaction/proven_tx.rs, objects/src/transaction/transaction_id.rs
This addresses #347 - i.e., we introduce `TransactionId` struct which uniquely identifies a transaction.
=> Add `TransactionId` struct

miden-lib/asm/miden/sat/internal/prologue.masm, miden-tx/src/verifier/mod.rs, mock/src/mock/chain.rs, objects/src/notes/mod.rs, objects/src/notes/nullifier.rs, objects/src/notes/script.rs, objects/src/transaction/consumed_notes.rs, objects/src/transaction/mod.rs, objects/src/transaction/proven_tx.rs, objects/src/transaction/transaction_id.rs, objects/src/transaction/tx_witness.rs, objects/src/transaction/utils.rs
This PR addresses a part of #350. Specifically, I removed `ConsumedNoteInfo` struct and replaced it with `Nullifier`. Using only nullifiers to compute consumed note commitment is sufficient since #283 as the verifier no longer needs to know script roots for the consumed notes.
The commitment to consumed notes is still computed as a sequential hash of `(nullifier, ZERO)` tuples instead of just as a sequential hash of nullifiers. I kept it this way primarily to keep the scope of changes relatively small and also because we may need to update the logic again to support #353.
=> Replace `ConsumedNoteInfo` with `Nullifier`

miden-lib/src/tests/test_prologue.rs, miden-tx/src/tests.rs, miden-tx/tests/common/mod.rs, miden-tx/tests/test_miden_faucet_contract.rs, miden-tx/tests/test_miden_note_scripts.rs, miden-tx/tests/test_miden_wallet.rs, mock/src/mock/block.rs, mock/src/mock/chain.rs, mock/src/mock/transaction.rs, objects/src/block/header.rs, objects/src/notes/origin.rs, objects/src/transaction/consumed_notes.rs
This PR changes type of `block_num` field in `BlockHeader` to `u32` as block numbers will not exceed this value (at 3-second block intervals, this gives us 400+ years of runway).
=> Change `block_num` type to `u32`

miden-lib/asm/scripts/P2ID.masm, miden-lib/asm/scripts/P2IDR.masm
During the implementation of the SWAP script I saw that an import wasn't used in P2ID and corrected the documentation relative to the inputs to the script on P2ID & P2IDR scripts.
=> Removed unused import & improved documentation on P2ID & P2IDR scripts

miden-tx/tests/faucet_contract_test.rs, miden-tx/tests/p2id_script_test.rs, miden-tx/tests/p2idr_script_test.rs, miden-tx/tests/swap_script_test.rs, miden-tx/tests/wallet_test.rs
After adding the `SWAP` PR #363, I believe that we need to change the file structure and naming of files to continue growing the number of tests in an idiomatic way.
EX: We had the swap script tests in one separate file and p2id and p2idr swap scripts tests in one global "note_test" file
I propose in this PR: 
- Splitting different tests in their own files 
- Fixed the naming of the test files
- Fixed the used assertions
- Removed the _miden_ particle
=> Split test code, fix assertions and follow idiomatic test naming

objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/notes/inputs.rs, objects/src/notes/mod.rs, objects/src/notes/script.rs, objects/src/notes/vault.rs, objects/src/transaction/outputs.rs
This PR addresses #343 and #345. It also streamlines `serde` serialization of accounts and notes by implementing `Serialize` and `Deserialize` traits directly on these objects rather than providing serilization handlers for different fields.
=> Implement lazy hashing for note assets and inputs

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/kernels/tx/account.masm, miden-lib/src/tests/mod.rs, miden-lib/src/tests/test_account.rs, miden-lib/src/tests/test_asset.rs, miden-lib/src/tests/test_asset_vault.rs, miden-lib/src/tests/test_faucet.rs, miden-lib/src/tests/test_note.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/tests/test_tx.rs, miden-lib/src/transaction/errors.rs, miden-lib/src/transaction/events.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/mod.rs, miden-tx/src/executor/mod.rs, miden-tx/src/host/account_delta.rs, miden-tx/src/host/account_procs.rs, miden-tx/src/host/mod.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests.rs, miden-tx/tests/common/mod.rs, mock/src/lib.rs, mock/src/mock/host/account_procs.rs, mock/src/mock/host/mod.rs, mock/src/mock/mod.rs, mock/src/mock/transaction.rs, objects/src/accounts/code.rs, objects/src/accounts/stub.rs, objects/src/transaction/inputs.rs
This PR builds on #404 and partially addresses #273. Specifically, we no longer put the `proc_root |-> proc_index` map into the advice provider. Instead, we introduce `PushAccountProcedureIndex` event which the `TransactionHost` uses to populate the advice stack with the index of the relevant procedure.
Also, as a part of this PR I updated the tests to use `MockHost` - this resulted in quite a few changes in existing tests.
=> Event-based procedure index lookups

miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/src/transaction/inputs.rs, miden-tx/tests/common/mod.rs, miden-tx/tests/faucet_contract_test.rs, miden-tx/tests/p2id_script_test.rs, miden-tx/tests/p2idr_script_test.rs, miden-tx/tests/swap_script_test.rs, miden-tx/tests/wallet_test.rs, objects/src/transaction/inputs.rs
This PR refactors how we handle input notes in the advice provider and should close #273.
The new approach is to put the number of input notes onto the advice stack, and then read this number first as the part of `process_input_notes_data` procedure in the prologue. Then, if the number of notes is greater than 0, everything works as before, but if the number of notes is 0, we don't make any lookups into the advice map.
One other change, the data in the advice map under the input note key `NC` no longer contains number of notes (because this data is now on the advice stack).
Also, as a part of this PR I updated some docs in the prologue - but more needs to be updated to align with the latest terminology.
=> refactor: handling of input notes in the advice provider

miden-lib/asm/miden/kernels/tx/epilogue.masm, miden-lib/src/transaction/mod.rs, miden-tx/tests/p2id_script_test.rs, objects/src/transaction/outputs.rs
This PR is analogous to #407 but for output notes. The main changes are that if there are no output notes, the epilogue does not put anything under `[ZERO; 4]` into the advice map. This prevents potential collisions over `[ZERO; 4]` key in the advice map.
=> Refactor: handling of output notes in the advice provider

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/kernels/tx/account.masm, miden-lib/src/transaction/errors.rs, miden-lib/src/transaction/events.rs, miden-tx/src/error.rs, miden-tx/src/executor/mod.rs, miden-tx/src/host/account_delta.rs, miden-tx/src/host/mod.rs, mock/src/mock/host/mod.rs, objects/src/accounts/storage/mod.rs
This PR completes the move of account delta tracking into `TransactionHost` and closes #400.
As a part of this PR, I've refactored event handling in the `TransactionHost` and introduced `AccountDeltaTracker` struct.
=> Move account storage delta tracking into transaction host

miden-lib/src/notes/mod.rs, miden-lib/src/notes/utils.rs, miden-tx/tests/p2id_script_test.rs, miden-tx/tests/p2idr_script_test.rs, miden-tx/tests/swap_script_test.rs, objects/src/lib.rs
Enables generation of random word for note serial_num inside of the create_note function.
In this PR I propose:
- The addition of `rng` replacing the `serial_num` parameter in the `create_note` function enabling a better interface and internal randomness management.
- The splitting of the `create_note` function into multiple functions. One function for each note script. For now: `create_p2id_note()`, `create_p2idr_note()`, `create_swap_note()`. Making the function more modular.
- A refactor of the swap note return values from `Note` to `(Note, Word)` with `Word` being the serial_number used to generate the recipient, hence enabling consumption of the consumer generated `p2id` note.
Closing #368
New PR opened from #380 to follow code addition convention.
=> Replaced `serial_num` with `rng` for note creation

mock/src/mock/chain.rs, objects/src/errors.rs, objects/src/transaction/chain_mmr.rs, objects/src/transaction/inputs.rs
This PR refactors `ChainMmr` constructor so that it accepts `BlockHeader`'s instead of `(u32, Digest)` tuples. This approach is more convenient for how `ChainMmr` is used by the client.
Also, this PR adds a couple of checks to ensure `InputNotes` struct is constructed correctly (having these checks would have saved us a lot of debugging time last week).
=> Update `ChainMmr` constructor to take block headers

objects/Cargo.toml, objects/src/accounts/data.rs, objects/src/accounts/mod.rs
In this PR I propose the addition of the `AccountData` struct. 
This will enable serialisation and deserialisation of `Account` data for transport. 
For example passing an account from the node to the client. 
We need this struct to be able to pass not only the `Account` but also the `account_seed` and the `auth` data. 
Enabling correct import and use of the `Account`.
=> Added `AccountData` struct

miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/src/tests/test_prologue.rs, objects/src/errors.rs, objects/src/transaction/chain_mmr.rs, objects/src/transaction/inputs.rs
This PR updates the transaction prologue code to extend the chain MMR with the block header provided to the transaction and fixes #305. This is needed because the chain MMR provided to the transaction is one block behind the block against which transaction is executed. Thus, without this change, we would not be able to consume any notes created at the current block.
As a part of this PR I've also added `ChainMmr::add_block()` method. Even though it is used only for testing, I think it might be valuable to expose it publicly.
One thing that this PR doesn't test is whether authentication paths for the leaves tracked by the chain MMR are extended in the advice provider post update. This is non-trivial to test, and looking at the [mmr::add](https://github.com/0xPolygonMiden/miden-vm/blob/main/ …
=> Update prologue to extend chain MMR with the latest block header

Cargo.toml, miden-tx/Cargo.toml
This PR adds `concurrent` feature to `miden-tx` crate. This should enable concurrent proof generation by transaction prover.
=> Add concurrent feature to `miden-tx`

Cargo.toml, miden-lib/Cargo.toml, miden-lib/src/tests/test_account.rs, miden-tx/Cargo.toml, mock/Cargo.toml, mock/src/mock/block.rs, mock/src/mock/chain.rs, objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/accounts/code.rs, objects/src/accounts/storage/mod.rs, objects/src/lib.rs, objects/src/notes/mod.rs
This PR updates `SimpleSmt` usage to be in line with https://github.com/0xPolygonMiden/crypto/pull/245.
This is a replacement for #426.
=> Update `SimpleSmt` usage as per latest crypto crate updates

miden-tx/src/error.rs
This replaces the previous `(u32, NodeIndex)` tuple which is no longer relevant.
=> Change `DataStore::NoteNotFound` variant to take `NoteId`

docs/src/introduction.md
A small update on our doc's intro section. 
I introduced a section about the Status and features. This is also to align the docs with what we have on the Miden VM, see [here](https://0xpolygonmiden.github.io/miden-vm/intro/main.html).
I also added the description above to use "Privacy Scales Better" consistently.
=> docs: update on the intro section

miden-lib/asm/miden/kernels/tx/constants.masm, miden-lib/asm/miden/kernels/tx/epilogue.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/note.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/kernels/tx/tx.masm, miden-lib/src/tests/test_prologue.rs, miden-lib/src/tests/test_tx.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/memory.rs, miden-lib/src/transaction/outputs.rs, miden-tx/tests/assets/test.masm, miden-tx/tests/faucet_contract_test.rs, miden-tx/tests/swap_script_test.rs, mock/src/lib.rs, mock/src/mock/notes.rs, mock/src/procedures.rs, objects/src/lib.rs, objects/src/notes/assets.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/transaction/inputs.rs, objects/src/transaction/mod.rs, objects/src/transaction/outputs.rs
This PR removes `num_assets` from `NoteMetadata` as described in #281. As a side effect, it will also close #342.
Other small changes in this PR:
- Fixed an issue with note memory layout where input notes could have overlapped with output notes.
- Updated terminology to "input" and "output" notes in some places (a more comprehensive update will come later).
- Consolidated constants.
- Moved procedures related to output notes from the `epilogue` to `note` module in the kernel.
=> Remove `num_assets` from note metadata

.github/workflows/ci.yml, Makefile, mock/src/constants.rs, objects/src/accounts/mod.rs, objects/src/accounts/seed.rs
In this PR I propose the addition of `release` and `concurrent` flag to the `Makefile` and `CI` of miden-base to enable faster `local` and `CI` test runs
Closes: #433
=> Refactor `Makefile` to enable `release` and `concurrent` flags

objects/src/notes/note_id.rs
As suggested to more easily convert from strings to `NoteId` on the client
=> Add `NoteId::try_from_hex`

docs/src/introduction/getting-started.md
After discussion with @Dominik1999 and @hackaugusto we decided to propose the addition of a getting started guide enabling a newcomer to user the core features of the Miden rollup.
I have been able to deploy an EC2 instance on AWS running the node. We are able to send queries and get responses from it's `RPC`. We can now use it as a testing ground for the Miden rollup.
Depends on: https://github.com/0xPolygonMiden/miden-node/pull/200
=> Add getting started `node` <=> `client` tutorial

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/kernels/tx/constants.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/note.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/note.masm, miden-lib/asm/note_scripts/P2ID.masm, miden-lib/asm/note_scripts/P2IDR.masm, miden-lib/asm/note_scripts/SWAP.masm, miden-lib/src/notes/mod.rs, miden-lib/src/tests/test_note.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/memory.rs, mock/src/builders/note.rs, mock/src/lib.rs, objects/src/lib.rs, objects/src/notes/inputs.rs, objects/src/notes/mod.rs, objects/src/notes/nullifier.rs
This addresses the remaining part of #281 (i.e., enables a variable number of inputs per note). The main changes are:
- Refactored `NoteInputs` struct to support variable number of values.
- Modified transaction kernel (prologue and note sections).
- Fixed an separate issue where nullifier section for consumed notes was previously too small (i.e., could fit only 512 nullifiers without overlapping with other data).
- Fixed new clippy warnings (had to bump up Rust version).
Due to refactoring of the `NoteInput` struct, changes in this PR may affect miden client and node.
=> Enable variable number of note inputs

objects/src/lib.rs
This constant is used in different repos when needing to setup a verifier.
=> Add constant `MIN_PROOF_SECURITY_LEVEL`

miden-lib/src/tests/test_prologue.rs, miden-tx/src/compiler/mod.rs, miden-tx/src/executor/mod.rs, objects/src/transaction/tx_script.rs
This PR removes unneeded `mut` modifiers from transaction compiler and transaction executor.
=> Remove unneeded muts

objects/src/accounts/mod.rs
In this PR I propose the addition of `Account::set_nonce()`. For different use cases we will need to manipulate the nonce of accounts. 
Will help us close: https://github.com/0xPolygonMiden/miden-node/issues/223
=> Add `Account::set_nonce()` function

objects/src/notes/nullifier.rs
These changes are needed for wider use of `Nullifier` type.
=> Implemented `Display` and `Ord` for `Nullifier`

miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/tests/test_asset_vault.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/outputs.rs, miden-tx/src/host/account_delta.rs, mock/src/lib.rs, mock/src/mock/block.rs, mock/src/procedures.rs, mock/src/utils.rs, objects/src/accounts/account_id.rs, objects/src/accounts/code.rs, objects/src/accounts/mod.rs, objects/src/accounts/seed.rs, objects/src/accounts/storage/slot.rs, objects/src/assets/fungible.rs, objects/src/assets/mod.rs, objects/src/assets/nonfungible.rs, objects/src/assets/token_symbol.rs, objects/src/assets/vault.rs, objects/src/notes/assets.rs, objects/src/notes/envelope.rs, objects/src/notes/inputs.rs, objects/src/transaction/inputs.rs, objects/src/transaction/outputs.rs
This PR updates the code to be compatible with new 0.8 version of the Winterfell.
This update mostly contains changes in `Felt` creation, since casting of `u64` to `FieldElement` was removed. It also updates the serialization and deserialization of the structs, which contain vectors of `Felts` or `RpoDigests`.
=> Update code to be compatible with Winterfell 0.8

docs/src/introduction/getting-started.md
Update on the `getting-started` section. 
I didn't consume the p2id note using the note-id. I used `miden-client tx new consume-notes <AccountID>` (as described in our tutorial).
But that led to `invalid account delta: InconsistentNonceUpdate("nonce updated for empty delta")`. It kind a makes sense, but the error message was a bit misleading. 
When I used `miden-client tx new consume-notes <AccountID> <NoteID>` it worked.
Maybe we need a different error message for that @igamigo ?
=> update on the getting started section for clarity

Cargo.toml, miden-lib/Cargo.toml, miden-tx/Cargo.toml, objects/Cargo.toml
This small PR changes Miden VM crates dependencies from git link to crate version.
=> Change git VM dependency to crate version

miden-tx/src/error.rs, miden-tx/src/executor/data.rs
after [a discussion](https://github.com/0xPolygonMiden/miden-client/pull/188#discussion_r1503326091) on one of the miden client's PRs we decided to add a variant to the DataStoreError to handle double spend errors (trying to consume an already consumed note) since we're currently using the `DataStoreError::InternalError` variant and it's less descriptive.
Also updated the `get_transaction_inputs` function documentation to consider the new variant.
=> feat: add DataStoreError double spend variant

objects/src/notes/mod.rs, objects/src/transaction/proven_tx.rs
add account/note details to ProvenTransaction https://github.com/0xPolygonMiden/miden-base/issues/403
=> objects: add account/note details to ProvenTransaction #403

Cargo.toml, miden-tx/Cargo.toml, mock/Cargo.toml, mock/src/builders/mod.rs, mock/src/builders/tx.rs, objects/src/notes/envelope.rs, objects/src/notes/note_id.rs, objects/src/notes/nullifier.rs, objects/src/transaction/mod.rs, objects/src/transaction/outputs.rs
Adds a mock builder for proven transactions.
Prep work for https://github.com/0xPolygonMiden/miden-node/issues/79
Note: This is based on top of #479 , which fixes the clippy warnings.
=> mock: add proven tx builder

objects/src/notes/mod.rs, objects/src/transaction/proven_tx.rs
This is required by the block_producer, which sends the ProvenTransactions across different tasks.
=> bugfix: ProvenTransaction must be Send

miden-lib/src/transaction/mod.rs
The current error looks like this:
```
---- tests::test_epilogue::test_epilogue stdout ----
thread 'tests::test_epilogue::test_epilogue' panicked at miden-lib/src/transaction/mod.rs:82:14:
kernel is well formed: ParsingError("malformed instruction 'assertz.ERR_FAUCET_RESERVED_DATA_SLOT': expected format `assertz.err=<code>`")
```
This fixes the assert message so it reads better:
```
---- tests::test_epilogue::test_epilogue stdout ----
thread 'tests::test_epilogue::test_epilogue' panicked at miden-lib/src/transaction/mod.rs:82:14:
kernel must be well formed: ParsingError("malformed instruction 'assertz.ERR_FAUCET_RESERVED_DATA_SLOT': expected format `assertz.err=<code>`")
```
=> kernel: improve error message

.pre-commit-config.yaml, mock/src/mock/block.rs, objects/Cargo.toml, objects/src/block/header.rs
As requested [here](https://github.com/0xPolygonMiden/miden-node/pull/260#discussion_r1514047173).
This should be released, since it is a block to release the `miden-node`.
=> mock: add mock constructor to BlockHeader behind testing feature

README.md, miden-lib/README.md, miden-tx/README.md, mock/README.md
This PRs updates the Readme file to follow a similar structure as the miden-vm.
The overview/status/features has the same content as https://0xpolygonmiden.github.io/miden- base/ . Besides that I added flags and a crates overview.
=> readme: prepare it for a release

objects/src/transaction/tx_args.rs
This PR removes `Option` wrapper from `note_args` field in `TransactionArgs`. This is a purely internal change and should not have any effect on external interfaces.
=> Remove `Option` from `note_args` field

miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, mock/src/mock/account.rs, objects/src/accounts/storage/mod.rs
This small PR is a follow-up to #513 to use storage slot constructors whenever possible with the primary intent of simplifying the code a bit.
=> Use dedicated storage slot constructors whenever possible

objects/src/transaction/proven_tx.rs
Implemented `validate` method for `ProvenTransaction`. Automatically validating `ProvenTransaction` during building and deserializing.
Resolves https://github.com/0xPolygonMiden/miden-base/issues/528
=> Implemented proven transaction validation

README.md
In this PR I propose to fix the README.md badges.
Fixed links to ci jobs + removed the crates.io badge because not relevant in the case of the base.
Addresses this comment: https://github.com/0xPolygonMiden/miden-base/pull/534#discussion_r1537811876
=> Fix `README` badges

objects/src/transaction/proven_tx.rs
In this PR I improve the `serde` of `ProvenTransaction` from serialising (NoteId, Note) to Note.
Closes: #520
=> Improve `ProventTransaction` serialisation

.config/nextest.toml, .github/workflows/test.yml, Cargo.toml, Makefile.toml
Using `nextest` by default and setting up the timeout. The goal is to figure out what is causing issues on the CI.
=> tests: using nextest by default and enabling test timeouts

Cargo.lock, Cargo.toml
This PR updates Miden VM dependencies to use v0.9 versions published to crates.io.
=> Update miden VM dependencies to v0.9

Cargo.lock, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/outputs.rs, miden-tx/Cargo.toml, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/accounts/mod.rs, objects/src/notes/mod.rs
This PR should hopefully fix test flakiness described in #566. The main chain is to use seeded PRNG for generating Falcon keys instead of using OS-provided randomness.
=> Use seeded RNG for falcon secret key generation

objects/src/accounts/data.rs
Changes the seed to `[u8;32]` instead of `[u8;40]` for consistency with the new key generation code. This will have to be reflected in the node as well at the moment of account generation.
=> Update `AccountData`'s auth seed

objects/src/accounts/seed.rs
I stumbled upon math overflow on seed generation during tests when initial seed is generated randomly.
```
thread 'db::tests::test_sql_select_accounts' panicked at /Users/polydez/.cargo/git/checkouts/miden-base-c72873dca0cede8b/d6af2ae/objects/src/accounts/seed.rs:35:9:
attempt to add with overflow
```
=> Fixed account seed generation math overflow

objects/src/block/note_tree.rs
This PR changes `BlockNoteTree:get_merkle_path` which returned path of length 21 to the note leaf to `BlockNoteTree::get_note_path()` which returns the path of length 20 to the parent node of note and note metadata.
Also, `BlockNoteTree::note_index()` is made public.
=> Return path to note parent from `BlockNoteTree`

miden-lib/src/transaction/inputs.rs, miden-tx/src/error.rs, miden-tx/src/prover/mod.rs, objects/src/errors.rs, objects/src/transaction/transaction_id.rs
We were originally setting the initial `Account` (`tx_witness.account()`) where we want to propagate the latest account state. This fixes the account hash mismatch issue we were seeing from the client when executing transactions with onchain accounts.
Additionally, this also applies the fix discussed on #529.
=> fix: Account details propagation

objects/src/accounts/code.rs, objects/src/accounts/data.rs
We were getting a deserialization error on the node when submitting a proven mint transaction:
```bash
cargo run --release --features testing,concurrent tx new mint 0x031cb9e685e6f6fa 0x29df14411f9b1667 20
Finished release [optimized] target(s) in 0.11s
Running `target/release/miden-client tx new mint 0x031cb9e685e6f6fa 0x29df14411f9b1667 20`
rpc api error: rpc request failed for submit_proven_transaction: status: InvalidArgument, message: "Invalid transaction", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 10 Apr 2024 03:56:04 GMT", "content-length": "0"} }
```
Particularly, the point of failure was when deserializing the `AccountDetails` of the `ProvenTransaction`. And more specifically when serializing the account's code during source …
=> fix: comment out serialization/deserialization of source locations

Cargo.lock, miden-lib/src/tests/test_account.rs, miden-lib/src/tests/test_asset.rs, miden-lib/src/tests/test_asset_vault.rs, miden-lib/src/tests/test_faucet.rs, miden-lib/src/tests/test_note.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/tests/test_tx.rs, miden-lib/src/transaction/inputs.rs, miden-tx/src/executor/mod.rs, miden-tx/src/host/mod.rs, miden-tx/src/tests.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/scripts/p2id.rs, miden-tx/tests/integration/scripts/p2idr.rs, miden-tx/tests/integration/scripts/swap.rs, miden-tx/tests/integration/wallet/mod.rs, mock/src/lib.rs, mock/src/mock/transaction.rs, objects/src/notes/recipient.rs, objects/src/notes/script.rs, objects/src/transaction/tx_args.rs
There were two bugs in the `NoteScript` encoding to `Vec<Felt>`. One off-by-one in the encoder, and a broken offset in the decoder.  This PR fixes both issues and adds a test.
This also re-enables the tests disabled by https://github.com/0xPolygonMiden/miden-base/pull/572
=> bugfix: fix note script serialization and re-enable tests

miden-tx/tests/integration/scripts/faucet.rs, objects/src/transaction/outputs.rs
Let user of the getter decide, if they need to copy it.
=> Avoid copying of note's metadata in getter

miden-tx/src/host/mod.rs, objects/src/notes/inputs.rs, objects/src/transaction/tx_args.rs
This PR puts note inputs for the expected output notes under a different key so that we can put un-padded note inputs into the advice provider.
This is a temporary fix as note inputs should always be under the same key (the note input commitment). The proper approach would be to store note inputs in the advice map as follows:
```
note_inputs_commitment |-> [num_inputs, padded_inputs]
```
=> Fix note input padding or expected output notes

CHANGELOG.md, miden-tx/src/compiler/mod.rs, miden-tx/src/executor/mod.rs
As requested by the Pioneers and early users, we need to be able to start the assembler with debug mode. So I added a new function to the Assmber constructor.
```
/// Returns a new Miden assembler instantiated with the transaction kernel and loaded with the
/// Miden stdlib, the midenlib and in debug mode.
pub fn assembler_with_debug() -> Assembler {
Assembler::default()
.with_library(&MidenLib::default())
.expect("failed to load miden-lib")
.with_library(&StdLibrary::default())
.expect("failed to load std-lib")
.with_kernel(Self::kernel())
.expect("kernel must be well formed")
.with_debug_mode(true)
}
```
We could also use an enum `DebugMode` and the existing function `assembler()` but then we need to change every instance. So it might be good to accept code duplication here.
=> Dominik add debug assembler

.github/workflows/lint.yml, Makefile.toml
In this PR I propose the addition of `fmt --check` enabling error logging in the CI.
Closes: #622
=> Add `fmt --check` to CI and makefile

Cargo.lock, miden-tx/src/compiler/mod.rs, miden-tx/src/executor/mod.rs
This PR makes sure when `TransactionExecutor` is instantiated in debug mode, transaction code will be executed in debug mode on the VM.
=> Properly handle debug mode in transaction executor

objects/src/accounts/delta/builder.rs, objects/src/accounts/delta/mod.rs, objects/src/accounts/mod.rs
Implements [this request](https://github.com/0xPolygonMiden/miden-base/issues/444#issuecomment-2068741278), the storage delta is now an argument.
Note: IMO it would be best to have builders for these, but so far we have put most builders for testing purposes on the mock crate, and it is unresolved how to use these factories. So I kept this simple.
=> storage delta as an argument (closes #444)

objects/src/notes/note_tag.rs
Remake of PR #644 as it was reverted.
Add Ord and PartialOrd derives to NoteTag so that we can use BTreeSetto check for duplicates efficiently.
=> Derive `Ord` and `PartialOrd` for `NoteTag`

miden-tx/src/host/tx_authenticator.rs
We have a [very similar enum](https://github.com/0xPolygonMiden/miden-client/blob/4bf6ad3943d60a4c7735cb4caa35a702ea81f8a7/src/store/mod.rs#L238) to `AuthSecretKey` in the client. If we implement `Serialize` for it we can make it the canonical enum and get rid of the client one.
=> feat: Serialize auth secret keys

CHANGELOG.md, miden-lib/src/tests/test_tx.rs, miden-tx/src/host/mod.rs, miden-tx/tests/integration/scripts/swap.rs, mock/src/mock/notes.rs, objects/src/notes/details.rs, objects/src/notes/mod.rs, objects/src/notes/note_header.rs, objects/src/notes/note_id.rs, objects/src/notes/nullifier.rs, objects/src/notes/recipient.rs, objects/src/transaction/outputs.rs, objects/src/transaction/proven_tx.rs
Addresses #645, specifically:
- Renames `NoteEnvelope` into `NoteHeader`.
- Introduces a new struct `NoteDetails` which consists of note assets and recipient.
- Refactors `Note` struct to be based on `NoteHeader` and `NoteDetails`.
=> Note object refactoring

CHANGELOG.md, Cargo.lock, miden-lib/src/notes/mod.rs, miden-lib/src/notes/utils.rs, miden-tx/tests/integration/scripts/swap.rs, objects/src/assets/mod.rs
This PR addresses #412 and #640, specifically:
- Updates `create_swap_note()` function to return `NoteDetails` for the payback note.
- Defines tag format for the SWAP note and sets it correctly.
There doesn't seem to be a test which tests creation of SWAP notes - we should probably add it at some point (maybe as a part of #446.
Also, we should think of a place where we document all used note tag formats (right now, the only one we have is SWAP).
=> Swap note updates

docs/introduction/get-started/p2p-public.md
The documentation missed the instruction for use to switch from miden-client-2 to miden-client. Since the txn is to be made from Account A, the directory has to be switched.
=> Added missing instruction to change directory from client 2 to client 1

CHANGELOG.md, Cargo.lock, miden-lib/build.rs, miden-lib/src/transaction/errors.rs, miden-tx/src/host/mod.rs, miden-tx/src/host/note_builder.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/notes/assets.rs
This PR implements `OutputNoteBuilder` similar to the one mentioned in https://github.com/0xPolygonMiden/miden-base/pull/614#discussion_r1590553160.
As a part of this, a few other changes were made in the made in `miden-objects`:
- Added `NoteAssets::add_asset()` method.
- Relaxed the condition in `NoteAssets` that at least one asset must be present. When the note asset list is empty, asset hash is set to `Digest::default()`.
=> Implement output note builder

objects/src/notes/mod.rs, objects/src/transaction/tx_args.rs
This PR enables calling `TransactionArgs::add_expected_output_note()` with anything that can be dereferenced as `NoteDetails`, which now includes both `Note` and `NoteDetails`.
=> Make `TransactionArgs::add_expected_output_note()` more flexible

objects/src/notes/script.rs
This was causing `UnexpectedEOF` when deserializing note scripts on the `miden-client` integration test that creates a custom note with custom note scripts. Seems like other scripts (like the usual P2ID) happened to have the correct value here and so we did not find this earlier.
I think this was also the cause for this error reported on Discord: https://discord.com/channels/893151281848406016/1114419272165376030/1235204660168495195
For a repro, here's what I used to debug:
<details>
```rust
const NOTE_SCRIPT: &str = "# Custom P2ID note script
#
use.miden::account
use.miden::note
use.miden::contracts::wallets::basic->wallet
proc.add_note_assets_to_account
push.0 exec.note::get_assets
dup.1 add
padw movup.5
dup dup.6 neq
while.true
dup movdn.5
mem_loadw call.wallet::receive_asset
movup.4 …
```
=> fix: Correct padding amount in code array when serializing note scripts 

miden-lib/src/notes/utils.rs
We found an issue when testing the flow for swap notes on `miden-client`. We were almost able to do a swap between 2 clients `A` and `B`. `A` ran the swap transaction, which created a note for `B` and the expected payback note. `B` consumed the note, and sent the remaining details to `A`. When we tried to consume the note with `A` we got this error:
```rust
transaction executor error: ExecuteTransactionProgramFailed(FailedAssertion { clk: 2261, err_code: 131074, err_msg: Some("P2ID scripts expect exactly 1 note input") })
```
The issue was with the way we create the payback note. VM already adds the padding to the inputs, so creating a note with `vec![X, ZERO, ZERO, ZERO]` will actually create it as if there were 4 different inputs instead of a single one. This causes an error when trying …
=> fix: create SWAP note inputs with a single element

docs/introduction/get-started/create-account-use-faucet.md, docs/introduction/get-started/p2p-private.md, docs/introduction/get-started/p2p-public.md
This PR does 2 things:
1. Cherry picks the merge commit from #692 from main
2. Updates the getting-started documentation to reflect the change in asset parsing. Now instead of `--faucet <faucet_id> <amount>` it is `--asset <amount>::<faucet_id>`
=> docs: update docs for asset parsing change on cli

CHANGELOG.md, bench-tx/src/utils.rs, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/scripts/p2id.rs, miden-tx/tests/integration/scripts/p2idr.rs, miden-tx/tests/integration/scripts/swap.rs, miden-tx/tests/integration/wallet/mod.rs, mock/src/builders/account.rs, mock/src/mock/account.rs, objects/src/accounts/data.rs, objects/src/accounts/mod.rs
=> refactor: split Account constructor into `new()` and `from_parts()`

CHANGELOG.md, miden-lib/asm/miden/tx.masm, miden-lib/src/tests/test_tx.rs
Adding a procedure that returns the note recipient hash for a custom note script and dynamic note input. This PR resolves #706 
This added procedure can only calculate the recipient hash for a note with a single input.
=> feat: add get_recipient_hash procedure 

CHANGELOG.md, miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/kernels/transaction/main.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/note.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/note.masm, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/errors.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/memory.rs, miden-tx/src/error.rs, miden-tx/src/host/note_builder.rs, objects/src/notes/inputs.rs, objects/src/notes/note_id.rs, objects/src/transaction/tx_args.rs
fixes #600 
- Removes the inputs length from the `NULLIFIER_COMMITMENT`, since now it is available in the `INPUTS_HASH`
- Removes the difference among consumed/created notes' inputs, now both encode the inputs prefixed by its length and padded to an even number of words
- Add the length as the first element to the `INPUTS_HASH`
- Update some of the documentation which was out of date
=> Fix issue 600

.github/workflows/lint.yml, .github/workflows/no-std.yml, .github/workflows/test.yml
I saw that we were not running the CI on merge to `next`.
This PR should fix this issue and make sure that the CI runs on pushes to `main` and `next`.
=> chore: add `next` as a branch for CI runs on merge

CHANGELOG.md, miden-lib/src/transaction/mod.rs, objects/src/errors.rs
This small PR adds a validation for `TransactionKernel::parse_output_stack` function to make sure that stack was properly cleaned (two last words are zero words) and overflowing addresses are empty.
=> Add stack validation for `TransactionKernel::parse_output_stack` 

docs/introduction/get-started/p2p-public.md
Account C sometimes gets incorrectly referred to as account B.
=> Fix inconsistent account naming in docs

CHANGELOG.md, objects/src/notes/file.rs, objects/src/notes/mod.rs
closes #715 
This PR adds a `NoteFile` object to represent serialized notes.
=> feat: Add `NoteFile` object

CHANGELOG.md, bench-tx/src/main.rs, miden-lib/src/notes/mod.rs, miden-tx/tests/integration/scripts/p2id.rs, miden-tx/tests/integration/scripts/p2idr.rs, miden-tx/tests/integration/scripts/swap.rs
Adresses [this comment](https://github.com/0xPolygonMiden/miden-node/pull/368#discussion_r1626329038).
Changes the note creation functions so that they receive a mutable reference to the rng.
=> fix: change `rng`type to `&mut R` in note creation functions

CHANGELOG.md, miden-lib/src/transaction/inputs.rs, miden-tx/src/compiler/mod.rs, miden-tx/src/kernel_tests/test_prologue.rs, miden-tx/src/prover/mod.rs, miden-tx/src/verifier/mod.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/inputs.rs, objects/src/transaction/mod.rs, objects/src/transaction/prepared_tx.rs, objects/src/transaction/proven_tx.rs, objects/src/transaction/transaction_id.rs, objects/src/transaction/tx_witness.rs
follow up to https://github.com/0xPolygonMiden/miden-base/pull/726
Instead of removing the `ToNullifier` trait, this replaces said trait with `ToInputNoteCommitment`. The change is mainly the additional of the `Option<NoteId>`, which will be used by https://github.com/0xPolygonMiden/miden-base/issues/353 .
The decision to keep the trait is due to code reuse. Mainly of the `NoteInputs` which does the validation for the number of inputs and computes the input notes commitment. The alternative of using a wrapper type ended duplicating validation code, when I tried to remove the duplicated the error handling become worse and introduced `unwraps`. Keeping the trait eliminates these concerns.
=> ToNullifier to ToInputNoteCommitment

CHANGELOG.md, objects/src/notes/file.rs
Adresses [this comment](https://github.com/0xPolygonMiden/miden-client/issues/371#issuecomment-2147197187):
> To differentiate between the two cases, we may need to modify the NoteFile in miden-base to change the details variant to something like NoteDetails(NoteDetails, Option<NoteTag>).
The idea is to have a way to import a note that is not intended to be tracked (when the tag is `None`). These notes will be specifically retrieved by ID from the node.
=> Add a tracking tag for `NoteFile`

objects/src/block/mod.rs
As follow-up of this conversation: https://github.com/0xPolygonMiden/miden-node/pull/377#discussion_r1631269898
Refactored `compute_tx_hash` in order to get rid of duplicate logics.
=> Refactored `compute_tx_hash`

bench-tx/src/utils.rs, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/transaction/inputs.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/accounts/data.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage/map.rs, objects/src/accounts/storage/mod.rs, objects/src/accounts/storage/testing.rs, objects/src/errors.rs, objects/src/testing/account.rs, objects/src/testing/storage.rs
This PR fixes the bug that the account storage delta was not applied for `set_map_item`. The application is also tested in `valid_account_delta_is_correctly_applied()`.
I changed `maps` in `AccountStorage` to `BTreeMap<u8, StorageMap>`
```Rust
pub struct AccountStorage {
slots: SimpleSmt<STORAGE_TREE_DEPTH>,
layout: Vec<StorageSlotType>,
maps: BTreeMap<u8, StorageMap>,
}
```
We need that in order to identify the StorageMaps when we want to apply the delta.
=> Apply account delta storage maps

.github/workflows/build.yml, CHANGELOG.md, Cargo.lock, Makefile, miden-tx/Cargo.toml, miden-tx/src/executor/data_store.rs, miden-tx/src/executor/mod.rs, miden-tx/src/testing/data_store.rs
In this PR I add conditional `async` for the DataStore trait using the [maybe-async-await](https://github.com/phklive/maybe-async-await) macro.
=> Implement `async` trait `DataStore` using `maybe-async-await` macro

bench-tx/src/utils.rs, miden-lib/asm/miden/kernels/tx/account.masm, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/transaction/inputs.rs, miden-tx/src/kernel_tests/test_account.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/accounts/data.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage/map.rs, objects/src/accounts/storage/mod.rs, objects/src/accounts/storage/slot.rs, objects/src/accounts/storage/testing.rs, objects/src/errors.rs, objects/src/testing/account.rs, objects/src/testing/storage.rs
Bugfix for set_item with a mapping.
This PR also:
- Add utils to create slot items, to make the tests a little bit shorter and more explicit
- Add a empty value for all slot types, so the serialization can skip empty maps and arrays in addition to empty values
- Removes some code duplication, adds some docs, and tries to stream line the account storage serde
=> Allow updates to all item slots

CHANGELOG.md, objects/src/accounts/mod.rs, objects/src/accounts/storage/mod.rs, objects/src/errors.rs
hacky fix for StorageMap for the patch release. 
A proper fix is in `next`
=> fixing StorageMap bug for patch release

miden-tx/src/testing/utils.rs, objects/src/testing/block.rs
after https://github.com/0xPolygonMiden/miden-client/pull/378 got merged, I tried the changes against miden base's `next` branch and got some errors:
```rust
mFragaBA> cargo check --target wasm32-unknown-unknown --features testing,async,wasm --no-default-features
error[E0425]: cannot find function `rand_array` in crate `rand`
--> /Users/lambda/.cargo/git/checkouts/miden-base-c72873dca0cede8b/97ae4cb/objects/src/testing/block.rs:589:31
|
589 |         let prev_hash = rand::rand_array().into();
|                               ^^^^^^^^^^ not found in `rand`
...
``` 
This is due to the recent refactor of the mock crate.  This PR adds some cfg guards in order to be able to compile for wasm.
=> fix: compilation for testing feature and wasm

miden-lib/asm/miden/kernels/tx/prologue.masm, miden-tx/src/kernel_tests/test_prologue.rs
The instruction movup.6 was accessing the parent's stack, the code worked because that value happened to be the same at position for movup.5. This change makes sure the `process_input_note` stays inside its declared stack.
=> bugfix: fix the stack access

miden-tx/src/tests.rs
A team wants to use notes without assets. I add an integration test to show how this can be done in Miden base. 
We need to add a test for this in the Miden client @igamigo
=> Add note without asset to the integration tests

miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/src/transaction/inputs.rs, objects/src/transaction/inputs.rs
Implements the changes to the kernel's prologue, which are necessary to support delayed note inclusion. Along side some code and documentation improvements.
closes #353
Currently marked as a draft because this PR is lacking tests.
=> kernel: add support for delayed note inclusion checks

objects/src/testing/account.rs
When I build the `miden-wasm` crate, I get this error in `miden-base`. It seems that for some reason, rust is having trouble inferring the type when `.into()` is used. 
```
error[E0283]: type annotations needed
--> /Users/dennisgarcia/Desktop/Work/polygon-miden/demox-miden-base/objects/src/testing/account.rs:138:68
|
138 |             if key != AccountStorage::SLOT_LAYOUT_COMMITMENT_INDEX.into() {
|                    -- type must be known at this point             ^^^^
|
= note: multiple `impl`s satisfying `u64: PartialEq<_>` found in the following crates: `core`, `serde_json`:
- impl PartialEq<serde_json::value::Value> for u64;
- impl<host> PartialEq for u64
where the constant `host` has type `bool`;
help: try using a fully qualified path to specify the expected types
|
138 | …
```
=> Type Annotations Error Fix for miden-wasm Crate

CHANGELOG.md, objects/src/transaction/inputs.rs, objects/src/transaction/proven_tx.rs
This is needed for testing simplification (it's so hard to construct new authenticated note just for testing purposes). With this change we can simply convert nullifier to authenticated input note commitment.
Related to https://github.com/0xPolygonMiden/miden-node/pull/390
=> Added conversion from `Nullifier` for `InputNoteCommitment`

objects/src/accounts/account_id.rs
Updated comment:
The higher two bits of the most significant nibble determines the ~~`account type`~~ `account storage mode`.
=> docs: fix a minor comment in account_id

objects/src/notes/header.rs, objects/src/notes/mod.rs, objects/src/transaction/outputs.rs
We need this method in order to easily calculate hash for output notes. Related to https://github.com/0xPolygonMiden/miden-node/pull/396
=> Implemented `OutputNote::hash`

CHANGELOG.md, Cargo.lock, docs/architecture/transactions/procedures.md, miden-lib/asm/miden/note.masm, miden-tx/src/tests/kernel_tests/test_note.rs
This PR implements `compute_inputs_hash` function in `note.masm` which allows to compute RPO hash of arbitrary number of Felt elements.
TODO:
=> Hash arbitrary number of elements in `masm`

bench-tx/src/main.rs, miden-tx/src/testing/tx_context.rs, miden-tx/src/testing/utils.rs, miden-tx/src/tests/kernel_tests/mod.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_epilogue.rs, miden-tx/src/tests/kernel_tests/test_faucet.rs, miden-tx/src/tests/kernel_tests/test_note.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, miden-tx/src/tests/mod.rs, objects/src/accounts/account_id.rs, objects/src/assets/fungible.rs, objects/src/assets/mod.rs, objects/src/assets/nonfungible.rs, objects/src/errors.rs, objects/src/notes/inputs.rs, objects/src/testing/assets.rs, objects/src/testing/notes.rs
builds on https://github.com/0xPolygonMiden/miden-base/pull/764
=> Tests cleanup 2

objects/src/testing/notes.rs
I found that `NoteBuilder` has inclusion proof field/method which is useless for `Note` object itself (it's needed for authenticated input note). Maybe it was left there due to note refactoring and not used anymore. In this PR I removed these field and method.
=> Removed useless inclusion proof from `NoteBuilder`

CHANGELOG.md, miden-lib/build.rs, miden-lib/src/transaction/inputs.rs, miden-tx/src/tests/kernel_tests/test_note.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/mod.rs, objects/src/transaction/tx_args.rs
This PR changes the `AdviceMap` inside `TransactionArgs` to `AdviceInputs`. This is needed so the `TransactionArgs` contain a `MerkleStore`, which was suggested in [this comment](https://github.com/0xPolygonMiden/miden-client/issues/243#issuecomment-2211464068) from `miden-client`.
=> feat: Change `TransactionArgs` to use `AdviceInputs`

CHANGELOG.md, miden-lib/asm/miden/kernels/tx/account.masm, miden-lib/asm/miden/kernels/tx/epilogue.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/kernels/tx/tx.masm
This small PR changes the setters in the `memory` module to make them more consistent: `Word` setters don't drop the setting `Word` anymore. 
Related issue: #773
=> Make memory setters consistent

CHANGELOG.md, miden-tx/src/tests/mod.rs, objects/src/accounts/delta/mod.rs, objects/src/accounts/mod.rs
This small PR removes the restriction from nonce to be changed without changing the account state, which was suggested in the related issue: #765.
=> Allow increasing an account's nonce without changing its state

.github/workflows/changelog.yml, .github/workflows/lint.yml, CHANGELOG.md, scripts/check-changelog.sh
In this PR I propose to add a warning if the `CHANGELOG.md` file has not been modified on PR.
=> Add warning for `CHANGELOG.md`

CHANGELOG.md, miden-lib/src/transaction/inputs.rs, objects/src/batches/note_tree.rs, objects/src/block/note_tree.rs, objects/src/constants.rs, objects/src/notes/location.rs, objects/src/transaction/inputs.rs
We had changed construction of `node_index_in_block` to `u32`, but the getter still converts it to `u64`. This PR fixes that.
=> Made `node_index_in_block` method return `u32`

CHANGELOG.md, miden-lib/src/notes/mod.rs
This tiny PR makes the `miden_lib::notes::build_swap_tag()` function public as it was requested in the corresponding issue: #806.
=> Make `build_swap_tag()` public

CHANGELOG.md, objects/src/notes/file.rs
As described by @bobbinth in his [comment on the note importing issue](https://github.com/0xPolygonMiden/miden-client/issues/405#issuecomment-2241365540), a new field that kept track of a possible block number where a note was committed was needed. With this change we don't need to sync a note from block 0 and now have a lower bound.
=> feat: Add `after_block_num` field to `NoteFile::NoteDetails`

CHANGELOG.md, objects/src/transaction/tx_args.rs
Addresses [this comment](https://github.com/0xPolygonMiden/miden-client/pull/471) from `miden-client`.
Implements `Serializable`, `Deserializable` and derives `PartialEq` and `Eq` for `TransactionScript`. These changes are needed to implement the serialization of `TransactionRequest` in `miden-client`.
=> feat: implement serialization and `Eq` for `TransactionScript`

CHANGELOG.md, miden-lib/asm/miden/contracts/wallets/basic.masm, miden-tx/src/testing/tx_context.rs, miden-tx/src/tests/mod.rs, objects/src/testing/account_code.rs
This small PR renames procedure in basic wallet from `cteate_note` to `create_note`. It also removes the duplicated `create_note` procedure from the account code.
=> Fit typo in `create_note` wallet procedure

Cargo.toml, miden-tx/src/testing/mock_chain.rs, objects/src/testing/account.rs, objects/src/testing/block.rs
Based on [some errors building the new version of the client for `wasm32-unknown-unknown`](https://github.com/0xPolygonMiden/miden-client/actions/runs/10533088664/job/29188479185), I looked at how the features from dependencies were being used for the web crate of the client and found that there were unnecessary imports. After leaving only the correct features, I found that there was a build error for `miden-base` (which can be reproduced by doing `cargo build --no-default-features --target wasm32-unknown-unknown --workspace --exclude miden-bench-tx --features testing`). This PR solves those errors.
```
error[E0432]: unresolved imports `winter_rand_utils::rand_array`, `winter_rand_utils::rand_value`
--> objects/src/testing/block.rs:6:25
|
6 | use winter_rand_utils::{rand_array, …
```
=> fix: Conditionally import dependency and pass RNG as param

miden-lib/asm/kernels/transaction/lib/account.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-tx/src/error.rs, miden-tx/src/host/account_procs.rs
This PR changes the number of account procedures back to 255. After thinking a bit more about it, I think 255 is probably large enough and will simplify dealing with potential edge cases.
=> Change max number of account procedures back to 256

CHANGELOG.md, miden-lib/src/transaction/mod.rs, miden-lib/src/transaction/outputs.rs, miden-tx/src/host/account_delta_tracker.rs, miden-tx/src/host/mod.rs, miden-tx/src/testing/mock_host.rs, objects/src/accounts/header.rs, objects/src/accounts/mod.rs, objects/src/errors.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/mod.rs, objects/src/transaction/outputs.rs
This small PR renames the `AccountStub` struct into `AccountHeader`.
Corresponding issue: #849.
=> Rename `AccountStub` into `AccountHeader` 

CHANGELOG.md, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-tx/src/error.rs, miden-tx/src/prover/mod.rs, miden-tx/tests/integration/wallet/mod.rs, objects/benches/account_seed.rs, objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/accounts/seed.rs, objects/src/errors.rs, objects/src/notes/note_tag.rs, objects/src/testing/account.rs, objects/src/testing/account_id.rs, objects/src/testing/storage.rs, objects/src/transaction/proven_tx.rs
This small PR renames the account storage type enum from `AccountStorageType` to `AccountStorageMode`, and also renames its variants as it was stated in the related issue #848.
=> Rename account storage type

CHANGELOG.md, objects/src/accounts/account_id.rs
As mentioned in [this comment](https://github.com/0xPolygonMiden/miden-client/pull/514#discussion_r1749293695), this PR adds the implementation of `Display` and `TryFrom<&str>` for AccountStorageMode.
=> feat: add `Display`, `FromStr` and `TryFrom<&str>` implementation to `AccountStorageMode`

CHANGELOG.md, miden-tx/README.md, miden-tx/src/lib.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/main.rs
=> feat: add `TransactionProver` trait, rename the `TransactionProver` struct to `LocalTransactionProver`

Cargo.lock, miden-lib/src/transaction/mod.rs, miden-tx/src/testing/executor.rs, miden-tx/src/testing/mock_chain.rs, miden-tx/src/testing/tx_context/builder.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_asset.rs, miden-tx/src/tests/kernel_tests/test_faucet.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/scripts/p2id.rs, objects/src/testing/account.rs, objects/src/testing/account_code.rs, objects/src/testing/assets.rs
Closes #643
Moves mock account code into a library that can be used to call the mock interface, removing the need for using MAST roots and maintaining the MAST root array. This might actually be a little less "clear" because in the past you could just search for the MAST root variables and get a feel for how the flow had to play out, but hopefully the test code is at least more concise and not as confusing with the removed workarounds and wrappers.
Also includes minor refactors to make some tests a bit more readable in general.
=> test: Remove calls by MAST root through account library

miden-lib/src/transaction/errors.rs, miden-tx/src/host/mod.rs, objects/src/accounts/storage/mod.rs, objects/src/errors.rs
This is a followup PR adding the requested changes after the merge of this PR: #811 
Additions:
- Helper function `get_num_storage_slots` added in `TransactionHost`
- Added `max` and `actual` to `StorageIndexOutOfBounds` and `InvalidStorageSlotIndex` errors
=> Followup: Refactored storage from `Smt` to `sequential hash`

.github/workflows/build.yml, Makefile, miden-tx/src/testing/executor.rs, miden-tx/src/testing/mock_chain.rs, miden-tx/src/testing/tx_context/builder.rs, miden-tx/src/testing/tx_context/mod.rs, objects/src/testing/account_code.rs
Since the `testing` feature flag is additive in the sense that it just adds code, it should be OK to add it directly to the `no-std` make target to detect potential problems in that code.
=> fix: Add testing feature flag to no-std build

Cargo.lock, objects/src/block/header.rs, objects/src/testing/block.rs
To correctly mock functional blocks we'd need this. Tests that rely on mocked blocks on the client would fail otherwise.
=> fix: Add kernel root to `Block::mock()`

CHANGELOG.md, bench-tx/src/utils.rs, docs/architecture/accounts.md, docs/architecture/transactions/overview.md, miden-lib/asm/miden/contracts/auth/basic.masm, miden-lib/asm/miden/contracts/wallets/basic.masm, miden-lib/asm/note_scripts/SWAP.masm, miden-lib/src/accounts/wallets/mod.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/testing/account_code.rs
This PR removes the `send_asset` procedure from the basic wallet. 
To send a note with some assets `create_note` and `move_asset_to_note` procedures should be used instead.
=> Remove `send_asset` procedure from the basic wallet

Cargo.lock, miden-lib/asm/kernels/transaction/lib/account.masm, miden-lib/asm/kernels/transaction/lib/epilogue.masm, miden-lib/asm/kernels/transaction/lib/memory.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/src/transaction/memory.rs, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/src/host/mod.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_asset_vault.rs, miden-tx/src/tests/kernel_tests/test_faucet.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs
This PR reworks memory layout to create an account data section, described in the FPI issue: #847
=> FPI: rework memory layout

CHANGELOG.md, Cargo.lock, objects/src/accounts/account_id.rs, objects/src/accounts/code/mod.rs, objects/src/accounts/code/procedure.rs, objects/src/accounts/delta/mod.rs, objects/src/accounts/delta/storage.rs, objects/src/accounts/delta/vault.rs, objects/src/accounts/mod.rs, objects/src/accounts/seed.rs, objects/src/accounts/storage/map.rs, objects/src/accounts/storage/mod.rs, objects/src/accounts/storage/slot/mod.rs, objects/src/accounts/storage/slot/type.rs, objects/src/assets/fungible.rs, objects/src/assets/mod.rs, objects/src/assets/nonfungible.rs, objects/src/assets/vault.rs, objects/src/constants.rs, objects/src/errors.rs, objects/src/transaction/proven_tx.rs
Implements a validation function to check that the serialized size of an `AccountDelta` does not exceed a defined limit.
fixes #830
The general approach was to implement `get_size_hint` on the `AccountDelta` and any type that it depended on, as reasonably possible (see below) and then check that size against the defined limit.
Fixes compilation of the crate under the `log` feature (file `seed.rs`), which was broken and prevented my IDE from using IntelliSense on the code I was working on, so I fixed it. The `async` feature however also fails to compile and is explicitly included from the checks it seems, but I don't understand why just yet.
None of the types that implement `Serializable` defined in `winter-utils` implement `get_size_hint`, which means all the primitive types. So calling …
=> feat: Validate Account Delta size limit

CHANGELOG.md, bin/tx-prover/src/server/generated/api.rs, miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/kernels/transaction/lib/epilogue.masm, miden-lib/asm/kernels/transaction/lib/memory.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/asm/kernels/transaction/lib/tx.masm, miden-lib/asm/miden/kernel_proc_offsets.masm, miden-lib/src/transaction/memory.rs, miden-lib/src/transaction/mod.rs, miden-lib/src/transaction/outputs.rs, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/src/errors/tx_kernel_errors.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests/kernel_tests/test_epilogue.rs, miden-tx/src/verifier/mod.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/transaction/outputs.rs, objects/src/transaction/proven_tx.rs
Closes #354 
Remaining work is testing that `ExecutedTransaction` and `ProvenTransaction` get the expected block expiration number, and addressing the questions I left in the comments.
=> feat: Set transaction expiry block delta

CHANGELOG.md, miden-lib/src/transaction/memory.rs, objects/src/constants.rs
We decided to move this constant into `miden-base` during review: https://github.com/0xPolygonMiden/miden-node/pull/506#discussion_r1782126954
=> Moved `MAX_NUM_FOREIGN_ACCOUNTS` into `miden-objects`

CHANGELOG.md, Cargo.lock, Makefile, bin/bench-tx/src/main.rs, bin/bench-tx/src/utils.rs, bin/tx-prover/src/server/generated/api.rs, miden-tx/Cargo.toml, miden-tx/src/executor/data_store.rs, miden-tx/src/executor/mod.rs, miden-tx/src/host/mod.rs, miden-tx/src/prover/mod.rs, miden-tx/src/testing/tx_context/mod.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/scripts/p2id.rs, miden-tx/tests/integration/scripts/p2idr.rs, miden-tx/tests/integration/wallet/mod.rs
This PR implements trait objects for user-facing structs instead of relying on crates as explained [here](https://github.com/0xPolygonMiden/miden-client/issues/366#issuecomment-2336779921).
Additionally, in order to make traits object-safe, `maybe_async_trait` (which relies on `async_trait`) is implemented for the correspondent traits.
=> feat: Implement `maybe_async_trait` and use trait objects

CHANGELOG.md, objects/src/assets/fungible.rs, objects/src/assets/mod.rs, objects/src/assets/nonfungible.rs
Implements `Serializable` for `FungibleAsset`.
I reconsidered whether it would make sense to
- forward the `Serializable` implementation from `Asset` to `FungibleAsset`, but `Asset` has a dedicated byte conversion implementation (`impl From<Asset> for [u8; Asset::SERIALIZED_SIZE]`) which makes more sense to keep using since it means that serialization is only defined in one place.
- forward the serialization and size hint implementation from `FungibleAssetDelta` to `FungibleAsset` but this is a special case. In the delta implementation we serialize the asset as 16 bytes whereas elsewhere it is serialized as 32 bytes.
The `Serializable` implementation reuses the 32-byte asset format even though it could be made more compact at 16 bytes (omitting the zeroes).
I guess the argument for …
=> Implement `Serializable` for `FungibleAsset`

miden-lib/asm/kernels/transaction/lib/account.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/src/host/account_procs.rs, miden-tx/src/tests/kernel_tests/test_tx.rs
This small PR changes the value in the advice map corresponding to the account code commitment.
Similar to the account storage data, the number of procedures was removed from the data provided to the advice map. Now the number of account procedures is computed from the number of field elements used to represent the procedure data.
=> Remove `num_procs` from account procedure data

bin/tx-prover/Cargo.toml, bin/tx-prover/README.md
Exposes `testing` and `concurrent` on the prover service features instead of assuming they should be enabled or disabled.
=> feat: Expose prover features

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/kernels/transaction/lib/tx.masm, miden-lib/asm/miden/kernel_proc_offsets.masm, miden-lib/asm/miden/tx.masm, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/src/tests/kernel_tests/test_epilogue.rs
Exposes procedures to get and set the expiration block number so that they can be used by the client
=> fix: export expiration block number procedures

CHANGELOG.md, miden-tx/src/executor/mast_store.rs, miden-tx/src/executor/mod.rs
This PR adds `TransactionExecutor::load_account_code()` method. It is meant to address some issues brought up in https://github.com/0xPolygonMiden/miden-base/issues/934. Specifically, it'll let the users of the executor to load foreign account code into the executor. It'll also enable associating a given set of procedures with a given account ID - and this will allow us to avoid modifying `TransactionArgs` as described in https://github.com/0xPolygonMiden/miden-base/issues/934#issuecomment-2438231043.
I made `TransactionExecutor::load_account_code()` take a mutable reference to `self` - @igamigo, will that be an issue for the client?
=> Implement account code loading into transaction executor

CHANGELOG.md, Cargo.lock, Makefile, miden-lib/src/notes/scripts.rs, miden-tx/src/auth/tx_authenticator.rs, miden-tx/src/executor/mast_store.rs
=> feat: Make structs `Send` + `Sync`, lazily initialize scripts

CHANGELOG.md, Cargo.lock, Makefile, bin/tx-prover/src/lib.rs, bin/tx-prover/src/prover.rs
closes #927
This PR changes the remote prover so that it connects on prove, this connection is not mantained and it's dropped at the end.
=> feat: `RemoteTransactionProver` lazy connect

CHANGELOG.md, miden-tx/src/executor/mod.rs, miden-tx/src/prover/mod.rs, objects/src/accounts/code/mod.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/tx_witness.rs
Transaction provers need foreign account codes to be loaded but there is no way to load them from a witness (ie, in the `TransactionProver` trait)
=> feat: Add account codes to witness

Cargo.lock, Makefile, bin/tx-prover/Cargo.toml, objects/Cargo.toml
As part of the prover proxy we added dependencies that the binary use, but we don't want to import when using `RemoteTransactionProver` (this should probably be separated some other way). We have a check for no-std builds, but it was not reached because the crate was excluded, so I changed the check to reach all crates, but only attempt to compile libraries and not binaries.
=> fix: WASM build for libraries

CHANGELOG.md, objects/src/transaction/executed_tx.rs
This PR adds two new methods to the `TransactionMeasurements` struct. 
- total()
- trace_length()
I also added a function to expose `tx_measurements` from the `TransactionExecutor` directly.
=> Make tx measurements public

CHANGELOG.md, miden-tx/Cargo.toml, miden-tx/src/executor/mod.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests/mod.rs
This PR adds two small methods to let users load custom libraries into `TransactionExecutor` and `LocalTransactionProver`. This is a temporary workaround which is needed to let users use user-defined libraries in account code. As mentioned in the comments, once we have support for library vendoring in the assembler, these methods can be removed.
cc @plafer and @bitwalker to highlight one use-case were we need library vendoring.
=> Add ability to load libraries into TX executor and prover

CHANGELOG.md, bin/bench-tx/src/main.rs, bin/bench-tx/src/utils.rs, miden-tx/src/testing/mock_chain/mod.rs, miden-tx/src/testing/tx_context/builder.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/scripts/swap.rs, objects/src/accounts/builder/mod.rs, objects/src/accounts/mod.rs
- Remove `AccountBuilder::build_testing` and add `AccountBuilder::build_existing`. This means we have a clear separation now between `AccountBuilder::build` which builds a new account and is available generally and `AccountBuilder::build_existing` which builds an existing account and is available only under `testing`.
- Make `Account::initialize_from_components` private and replace usages with `AccountBuilder`. It turns out that we don't need to build accounts with a specific `AccountId` anywhere in tests so those occurrences were changed to generate a new one instead.
- The `nonce` field in the `AccountBuilder` was no longer needed so I removed it. The nonce is set in `build` and `build_existing` directly.
- The methods on `MockChain` to add new accounts were all adding the build …
=> Revisit `Account::initialize_from_components` and add `AccountBuilder::build_existing`

objects/src/errors.rs
When changing the base branches to `next` in the Miden Client (https://github.com/0xPolygonMiden/miden-client/pull/617), one of the errors is caused because an element of `AssetError` is not `Send`. By changing this line the error in the client is fixed (tested it locally).
=> feat: add `Send` to internal error

miden-lib/build.rs
https://github.com/0xPolygonMiden/miden-base/pull/887 added a build script that builds `kernel_v0.rs`, but the script runs on changes to the file itself. I suspect this was the reason for test times doubling after that PR as pointed out in https://github.com/0xPolygonMiden/miden-base/issues/903.
This PR simply removes this rerun check. I doubt this check is the correct behaviour either way, since if it reruns based on changes to the `kernel_v0.rs`, it means it reruns every time the file is generated - which means the build script is triggered between each invocation of `cargo nextest` as well.
I've tested this in my personal repo - the run is here: https://github.com/eightfilms/miden-base/actions/runs/12064550221/job/33641593187 and is based on this branch: …
=> build(lib): do not run build script based on changes to `kernel_v0.rs`

objects/src/accounts/delta/vault.rs
This is needed for getting asset delta count without iteration over all of them.
=> feat: implement `count` method for (non)fungible asset deltas

objects/src/errors.rs
This requirement is needed for `anyhow` support.
=> refactor: require `Sync` for source of `InvalidFaucetAccountId`

CHANGELOG.md, Cargo.lock, bin/tx-prover/Cargo.toml, bin/tx-prover/src/commands/mod.rs, bin/tx-prover/src/proxy/mod.rs
Closes #986 
- Updates pingora crates to 0.4
- Uses Uuid v4 instead of u128.
- Adds polling time to the configuration file.
=> chore: proxy cleanup

CHANGELOG.md, Cargo.lock, bin/tx-prover/Cargo.toml, bin/tx-prover/README.md, bin/tx-prover/src/commands/mod.rs, bin/tx-prover/src/commands/proxy.rs, bin/tx-prover/src/commands/update_workers.rs, bin/tx-prover/src/proxy/mod.rs, bin/tx-prover/src/utils.rs
Closes #963 
Adds a command to add/remove workers from a running proxy. It updates the configuration file.
Can be used by running:
```bash
miden-tx-prover add-workers 100.23.55.33:8888 0.0.0.0:8080
miden-tx-prover remove-workers 67.44.36.17:5345 88.99.0.1:6543
```
It works by keeping both a list of available workers and another for all the workers in the proxy. The proxy can be updated only if the sender of the update is in the localhost.
=> feat: dynamic creation and removal of workers

CHANGELOG.md, Cargo.lock, bin/tx-prover/Cargo.toml, bin/tx-prover/README.md, bin/tx-prover/src/commands/mod.rs, bin/tx-prover/src/commands/proxy.rs, bin/tx-prover/src/commands/update_workers.rs, bin/tx-prover/src/commands/worker.rs, bin/tx-prover/src/main.rs, bin/tx-prover/src/proxy/mod.rs, bin/tx-prover/src/proxy/worker.rs, bin/tx-prover/src/utils.rs
This PR adds:
- Health Check endpoints to the remote prover using the `tonic-health` crate, which adds the required endpoints without the need of defining the methods in a `.proto` file.
- Add a background service in the Proxy that periodically checks the health of each worker and removes the ones that are not working.
=> feat: health check in worker

CHANGELOG.md, bin/tx-prover/README.md, bin/tx-prover/src/commands/mod.rs, bin/tx-prover/src/commands/proxy.rs, bin/tx-prover/src/proxy/mod.rs, bin/tx-prover/src/proxy/worker.rs
=> feat: remove workers from the proxy configuration file

docs/architecture/accounts.md, docs/index.md
In this PR I propose to update the `Accounts` section of the Miden documentation:
- more explanative
- more approachable for new developers
- shortened
- simplified
- re-phrased
- updated structure
=> [Docs]: Update `Accounts` section

CHANGELOG.md, Cargo.lock, bin/tx-prover/Cargo.toml, bin/tx-prover/README.md, bin/tx-prover/src/api/mod.rs, bin/tx-prover/src/commands/mod.rs, bin/tx-prover/src/commands/proxy.rs, bin/tx-prover/src/commands/worker.rs, bin/tx-prover/src/main.rs, bin/tx-prover/src/proxy/mod.rs, bin/tx-prover/src/utils.rs
=> feat: add tracing to worker and proxy

CHANGELOG.md, objects/src/accounts/account_id_prefix.rs, objects/src/block/header.rs
This PR adds two small quality of life methods to `AccountIdPrefix` and `BlockHeader`. Both stemming from comments in [this review](https://github.com/0xPolygonMiden/miden-client/pull/639#pullrequestreview-2522657129).
=> feat: account ID refactor additional methods

Cargo.lock, bin/tx-prover/Cargo.toml, bin/tx-prover/src/commands/proxy.rs, bin/tx-prover/src/error.rs, bin/tx-prover/src/lib.rs, bin/tx-prover/src/main.rs, bin/tx-prover/src/proxy/mod.rs, bin/tx-prover/src/proxy/worker.rs, bin/tx-prover/src/utils.rs
=> feat: add error for tx prover proxy

.github/workflows/lint.yml, Makefile, objects/src/accounts/component/template/storage/mod.rs, objects/src/accounts/component/template/storage/toml.rs, objects/src/testing/block.rs
- Add `no_std` Makefile recipes to `cargo check` and `cargo clippy` the no_std target.
- Fix the issues flagged by `make clippy-no-std` (unused variables in no_std).
- Add a CI check for `clippy-no-std` (totally optional I think, it would mostly find unused variables, but should not take much time anyway).
- I took this opportunity to add a `test-dev` command to execute the majority of tests (excluding slow ones like prove tests) in debug mode, convenient when iterating on a PR locally. I was missing this and always ran `cargo nextest` directly because the existing `make test-*` recipes all use release mode which takes minutes to compile alone. This target makes it convenient to run tests from all crates with one command. `make test-dev` takes roughly 30s for me, with the slowest tests …
=> Add `no_std` Makefile recipes

CHANGELOG.md, Cargo.lock, bin/tx-prover/Cargo.toml, miden-lib/Cargo.toml, miden-tx/Cargo.toml, objects/Cargo.toml, objects/benches/account_seed.rs, objects/src/accounts/account_id/seed.rs, objects/src/assets/mod.rs
Removes the multi-threaded account seed generation which appears to be slower than the single-threaded one according to the benchmark in #1056.
Adds [pprof](https://github.com/tikv/pprof-rs) profiler for the benchmarks to produce flamegraphs. I thought this might give some insight into where the difference between single- and multi-threaded seed generation comes, but iiuc this "on-cpu" flamegraph doesn't show context switching (as described in https://www.brendangregg.com/FlameGraphs/offcpuflamegraphs.html) and I did not go further down that rabbithole. I left the flamegraph code anyway in case it may be useful in the future, though if we don't want it I can also remove it.
closes #1056
=> Remove multi-threaded account seed generation

CHANGELOG.md, miden-lib/src/accounts/faucets/mod.rs
We need to use this values in the miden-client repo to avoid repetition. https://github.com/0xPolygonMiden/miden-client/issues/476
=> feat: make MAX_DECIMALS  public

CHANGELOG.md, miden-lib/asm/kernels/transaction/lib/account.masm, miden-lib/asm/kernels/transaction/lib/asset.masm, miden-lib/asm/kernels/transaction/lib/constants.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/asm/miden/account.masm, miden-lib/asm/miden/asset.masm, miden-lib/asm/miden/note.masm, miden-lib/asm/note_scripts/P2ID.masm, miden-lib/asm/note_scripts/P2IDR.masm, miden-lib/asm/shared/util/account_id.masm, miden-lib/asm/shared/util/asset.masm, miden-lib/asm/shared/util/note.masm, miden-lib/build.rs
After a lot of back and forth in #1002 I think that making a new PR is easier as the approach in this PR is more minimal than in the other PR and reverting those changes in #1002 is more work than applying the necessary changes to `next`.
This basically implements the conclusion from https://github.com/0xPolygonMiden/miden-base/pull/1002#issuecomment-2592841287
This is the approach with minimal changes to only deduplicate procedures across kernel and miden lib and reexporting procedures from where they were previously used so the public interface is the same.
The `util` module was put in a `shared` directory so we can use `Assembler::add_modules_from_dir` with namespace `kernel` to achieve the desired `kernel::util::module` namespacing. The alternative approach without the `shared` …
=> Move duplicate procedures to shared util modules

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/kernels/transaction/lib/account.masm, miden-lib/asm/kernels/transaction/lib/asset_vault.masm, miden-lib/asm/kernels/transaction/lib/epilogue.masm, miden-lib/asm/kernels/transaction/lib/prologue.masm, miden-lib/asm/kernels/transaction/lib/tx.masm, miden-lib/asm/kernels/transaction/main.masm, miden-lib/asm/miden/note.masm, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/src/host/mod.rs
Refactors the `get_account_map_item` kernel procedure to call an underlying `kernel::account::get_map_item` which is responsible for checking the slot type and retrieving the actual data.
Removes the extra decorator operations which I believe can now be removed due to https://github.com/0xPolygonMiden/miden-vm/issues/1122 being fixed.
Fixes some outdated MASM docs.
This implements #768 except for any event refactoring.
=> Add `kernel::account::get_map_item`

CHANGELOG.md, miden-lib/src/notes/mod.rs, miden-lib/src/transaction/mod.rs, miden-tx/src/testing/mock_chain/mod.rs, miden-tx/src/tests/kernel_tests/test_note.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, miden-tx/tests/integration/scripts/p2idr.rs, objects/src/block/header.rs, objects/src/notes/execution_hint.rs, objects/src/notes/file.rs, objects/src/notes/metadata.rs, objects/src/transaction/outputs.rs, objects/src/transaction/proven_tx.rs
=> feat: missing BlockNumber s

CHANGELOG.md, miden-tx/src/errors/mod.rs
In my previous PR i missed this `u32`.
=> fix: missing BlockNumber update in error struct

CHANGELOG.md, miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-tx/src/testing/mock_chain/mod.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/tests/integration/wallet/mod.rs, objects/src/accounts/account_id/id_anchor.rs, objects/src/block/block_number.rs, objects/src/constants.rs, objects/src/lib.rs, objects/src/testing/block.rs, objects/src/transaction/chain_mmr.rs, objects/src/transaction/mod.rs
This PR removes `GENESIS_BLOCK` public constant in favor of `BlockNumber::GENESIS`. It also removes the redundant `BlockHeader` re-export from the root namespace.
=> Remove `GENESIS_BLOCK` public constant

Cargo.lock, Cargo.toml, miden-lib/build.rs, miden-lib/src/transaction/errors.rs, miden-lib/src/transaction/events.rs, miden-lib/src/transaction/mod.rs, miden-lib/src/transaction/procedures/kernel_v0.rs, miden-tx/Cargo.toml, miden-tx/src/host/account_procs.rs, miden-tx/src/host/mod.rs, miden-tx/src/testing/executor.rs, miden-tx/src/testing/mock_host.rs, miden-tx/src/testing/tx_context/builder.rs, miden-tx/src/testing/tx_context/mod.rs, miden-tx/src/tests/kernel_tests/mod.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_asset.rs, miden-tx/src/tests/kernel_tests/test_asset_vault.rs, miden-tx/src/tests/kernel_tests/test_epilogue.rs, miden-tx/src/tests/kernel_tests/test_faucet.rs, miden-tx/src/tests/kernel_tests/test_note.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, objects/Cargo.toml, objects/src/lib.rs, objects/src/transaction/tx_args.rs
This PR updates the code of the `miden-base` to be compatible with the next version of the Miden VM.
=> Migrate to the VM `next` branch (v0.12.0)

CHANGELOG.md, miden-lib/asm/miden/note.masm, miden-tx/src/errors/mod.rs, miden-tx/src/tests/mod.rs, objects/src/accounts/code/mod.rs, objects/src/accounts/mod.rs, objects/src/errors.rs
Turns miden-vm and miden-crypto errors into source errors now that we've upgraded to the latest versions.
Removes two outdated TODOs that were handled in previous PRs.
Builds on top of #1084.
closes #981
=> Turn miden-vm and miden-crypto errors into source errors

crates/miden-lib/build.rs, crates/miden-lib/src/account/auth/mod.rs, crates/miden-lib/src/account/faucets/mod.rs, crates/miden-lib/src/account/wallets/mod.rs
This PR reintroduces the changes from #960 parts of which have somehow gone missing on `next`.
This mainly compiles account components from the files introduced in #960 instead of defining the code in constants.
=> Reintroduce moving pre-defined account components' source code into masm files

CHANGELOG.md, Cargo.lock, crates/miden-objects/Cargo.toml
This release incorporates changes from #1100 and #1103.
=> Prepares v0.7.1 release of `miden-objects` crate

CHANGELOG.md, bin/proving-service/src/commands/mod.rs, bin/proving-service/src/commands/proxy.rs, bin/proving-service/src/commands/update_workers.rs, bin/proving-service/src/proxy/health_check.rs, bin/proving-service/src/proxy/mod.rs, bin/proving-service/src/proxy/update_workers.rs, bin/proving-service/src/proxy/worker.rs, bin/proving-service/src/utils.rs
This PR adds a new service to the proxy server, which is in charge of updating the workers in the load balancer. This allows of removing the responsibility from the proxy itself.
closes #1003
=> feat: update workers service in proxy

CHANGELOG.md, crates/miden-objects/src/account/data.rs, crates/miden-objects/src/account/file.rs, crates/miden-objects/src/account/mod.rs
Closes #1101
Renames the AccountData struct to AccountFile.
=> Rename AccountData struct

crates/miden-tx/src/tests/kernel_tests/test_tx.rs
This small PR adds a new memory test for FPI to check the correctness of the memory layout during the foreign procedure invocations of two different foreign accounts.
=> Enhance FPI tests

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/api.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/asm/kernels/transaction/lib/tx.masm, crates/miden-lib/asm/miden/kernel_proc_offsets.masm, crates/miden-lib/asm/miden/tx.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-tx/src/tests/kernel_tests/test_tx.rs
This small PR implements the `get_block_timestamp` procedure in the `miden::tx` file, adding the corresponding `tx_get_block_hash` procedure to the kernel.
=> Implement `get_block_timestamp` procedure.

CHANGELOG.md, Cargo.lock, crates/miden-objects/Cargo.toml, crates/miden-objects/src/batch/batch_id.rs, crates/miden-objects/src/batch/note_tree.rs, crates/miden-objects/src/batch/proposed_batch.rs, crates/miden-objects/src/batch/proven_batch.rs, crates/miden-objects/src/transaction/chain_mmr.rs
This is needed for the remote batch prover (#1131).
This PR depends on a fix on Winterfell (https://github.com/facebook/winterfell/pull/366), due to a bug in the `Proof` and `Context` serialization.
=> feat: add de/serialization for proposed batch

CHANGELOG.md, crates/miden-objects/src/note/nullifier.rs
based on [this comment](https://github.com/0xPolygonMiden/miden-client/pull/650#discussion_r1954620127)
The Nullifier should have a method to get its prefix. The prefix is sent in the sync state request to get nullifier updates without exposing the specific nullifiers that the client is interested in.
=> feat: add `prefix` to `Nullifier`

CHANGELOG.md, Cargo.lock, crates/miden-block-prover/src/tests/proposed_block_errors.rs, crates/miden-block-prover/src/tests/proposed_block_success.rs, crates/miden-block-prover/src/tests/proven_block_success.rs, crates/miden-block-prover/src/tests/utils.rs, crates/miden-objects/src/batch/proposed_batch.rs, crates/miden-objects/src/batch/proven_batch.rs, crates/miden-objects/src/block/proposed_block.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/transaction/executed_tx.rs, crates/miden-proving-service-client/Cargo.toml, crates/miden-proving-service-client/src/proving_service/batch_prover.rs, crates/miden-tx-batch-prover/src/errors.rs, crates/miden-tx-batch-prover/src/local_batch_prover.rs, crates/miden-tx-batch-prover/src/tests/proposed_batch.rs, crates/miden-tx/src/testing/mock_chain/mod.rs
- Batches: Check that none of the transactions in a batch are expired and tests expired and unexpired transactions.
- Batches: Removes the `BatchNoteTree` from `ProposedBatch` and `ProvenBatch`.
- Block: Check that the batches included in the block are unexpired and tests expired and unexpired batches.
- Rename `ProvenBatch::new` -> `ProvenBatch::new_unchecked` to match `ProvenBlock::new_unchecked` (both of which don't do any validation).
- Simplify the transaction reference block check in the batch to avoid allocating a new `BTreeSet`.
- Rename `BatchProveError` to `ProvenBatchError` to align with `ProvenBlockError`, `ProposedBlockError` and `ProposedBatchError`.
closes #1156
closes #1159
closes #920
=> Check for expired transactions and batches

CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, bin/proving-service/Cargo.toml, bin/proving-service/README.md, bin/proving-service/src/api/mod.rs, bin/proving-service/src/commands/worker.rs, bin/proving-service/src/generated/mod.rs, crates/miden-objects/src/block/account_update_witness.rs, crates/miden-objects/src/block/nullifier_witness.rs, crates/miden-objects/src/block/proposed_block.rs, crates/miden-proving-service-client/Cargo.toml, crates/miden-proving-service-client/README.md, crates/miden-proving-service-client/src/proving_service/batch_prover.rs, crates/miden-proving-service-client/src/proving_service/block_prover.rs, crates/miden-proving-service-client/src/proving_service/generated/mod.rs, crates/miden-proving-service-client/src/proving_service/mod.rs, crates/miden-proving-service-client/src/proving_service/tx_prover.rs
Closes #1034 
This PR adds a block prover to the `miden-proving-service` workers, and a `RemoteBlockProver` in the `miden-proving-service-client` crate.
=> feat: add remote block prover

CHANGELOG.md, crates/miden-block-prover/src/local_block_prover.rs, crates/miden-block-prover/src/tests/proposed_block_errors.rs, crates/miden-block-prover/src/tests/proposed_block_success.rs, crates/miden-block-prover/src/tests/proven_block_error.rs, crates/miden-block-prover/src/tests/proven_block_success.rs, crates/miden-objects/src/batch/proposed_batch.rs, crates/miden-objects/src/batch/proven_batch.rs, crates/miden-objects/src/block/note_tree.rs, crates/miden-objects/src/block/proposed_block.rs, crates/miden-objects/src/block/proven_block.rs, crates/miden-tx/src/testing/mock_chain/mod.rs
Allow blocks with empty batches so we can build new blocks in the node even if no transactions or batches are available.
Also clarifies comments in the proposed batch.
Consistently name `created_nullifiers` method across `ProposedBatch`, `ProposedBlock` and `ProvenBlock`.
=> Allow blocks with empty batches

crates/miden-block-prover/src/local_block_prover.rs, crates/miden-proving-service-client/src/proving_service/batch_prover.rs, crates/miden-proving-service-client/src/proving_service/block_prover.rs, crates/miden-tx-batch-prover/src/local_batch_prover.rs
derives `Clone` to the remote and local batch provers.
We use it in the node side to send a copies of the client when spawning batch builders.
=> fix: make batch provers clonable

Cargo.toml, crates/miden-block-prover/src/tests/proposed_block_errors.rs, crates/miden-block-prover/src/tests/proven_block_success.rs, crates/miden-objects/src/block/header.rs, crates/miden-objects/src/block/proven_block.rs, crates/miden-objects/src/transaction/chain_mmr.rs, crates/miden-tx-batch-prover/src/tests/proposed_batch.rs, crates/miden-tx/src/testing/mock_chain/mod.rs, crates/miden-tx/src/tests/kernel_tests/test_prologue.rs
Remove `Copy` from `BlockHeader`.
closes https://github.com/0xPolygonMiden/miden-base/issues/1076
Technically, the issue says we should enforce the clippy lint, but I tried setting those up and I think it's easier to enable them all at once in a separate PR. Should I create an issue for adding pedantic lints like in https://github.com/0xPolygonMiden/miden-node/pull/623?
=> Remove `Copy` from `BlockHeader`

.github/workflows/lint.yml
Pin cargo machete to a specific ~~commit~~ version since the latest version requires Rust Edition 2024.
=> Pin cargo machete to a specific version

CHANGELOG.md, Cargo.lock, crates/miden-objects/Cargo.toml, crates/miden-objects/src/account/account_id/address_type.rs, crates/miden-objects/src/account/account_id/mod.rs, crates/miden-objects/src/account/account_id/network_id.rs, crates/miden-objects/src/account/account_id/v0/mod.rs, crates/miden-objects/src/account/mod.rs, crates/miden-objects/src/errors.rs
Implement bech32 encoding for `AccountId`.
Copy of `AccountId::to_bech32` docs:
The encoding of an account ID into bech32 is done as follows:
- Convert the account ID into its `[u8; 15]` data format.
- Insert the address type [`AddressType::AccountId`] byte at index 0, shifting all other
elements to the right.
- Choose an HRP, defined as a [`NetworkId`], for example [`NetworkId::Mainnet`] whose string
representation is `mm`.
- Encode the resulting HRP together with the data into a bech32 string using the
[`bech32::Bech32m`] checksum algorithm.
This is an example of an account ID in hex and bech32 representations:
```text
hex:    0x140fa04a1e61fc900000126ef8f1d6
bech32: mm1qzgpgraqfg0xrlqqqqfxa7836czc9qzl
```
Having the address type at the very beginning is so that it can be decoded to …
=> Implement bech32 encoding for `AccountId`

CHANGELOG.md, crates/miden-block-prover/src/tests/proposed_block_errors.rs, crates/miden-block-prover/src/tests/proposed_block_success.rs, crates/miden-block-prover/src/tests/proven_block_error.rs, crates/miden-block-prover/src/tests/proven_block_success.rs, crates/miden-block-prover/src/tests/utils.rs, crates/miden-lib/asm/kernels/transaction/main.masm, crates/miden-objects/src/testing/constants.rs, crates/miden-tx-batch-prover/src/tests/proposed_batch.rs, crates/miden-tx/src/testing/mock_chain/mod.rs, crates/miden-tx/src/testing/tx_context/builder.rs, crates/miden-tx/src/tests/kernel_tests/test_note.rs, crates/miden-tx/src/tests/kernel_tests/test_prologue.rs, crates/miden-tx/src/tests/kernel_tests/test_tx.rs, crates/miden-tx/tests/integration/scripts/faucet.rs, crates/miden-tx/tests/integration/scripts/p2id.rs, crates/miden-tx/tests/integration/scripts/p2idr.rs, crates/miden-tx/tests/integration/scripts/swap.rs
Enable setting the timestamp on `MockChain::seal_block` and rename the existing `seal_block` to `seal_next_block` for convenience.
Small fixes: Remove unused testing constants and fix tx kernel `main.masm` output docs
fixes #788
=> Enable timestamp customization on `MockChain::seal_block`

crates/miden-lib/src/account/interface/component.rs
Should fix failing tests [here](https://github.com/0xPolygonMiden/miden-client/pull/781).
As an aside, there is probably some room for adding some util functions that help avoid these issues (eg, a `push_line()` function) or maybe a more builder-like approach
=> fix: Script builder newline

.github/workflows/lint.yml
This reverts #1181 since we are now on Rust Edition 2024.
part of https://github.com/0xPolygonMiden/miden-base/issues/1182
=> Revert cargo machete pin

Cargo.lock, Cargo.toml
This PR updates `miden-vm` dependencies to be pulled from crates.io.
=> Use crates.io versions for miden-vm dependencies

crates/miden-block-prover/src/tests/utils.rs
Digging through the miden-base repo and found this super minor misspelling of a word. This is a PR to fix it. 
This probably doesn't need a changelog.
=> Fix minor spelling of `receiver`

.github/workflows/book.yml, .github/workflows/build.yml, docs/book.toml
In this PR I: 
- Backport the changes made to `book.toml` in the miden-node
- Update the `book.toml` file to have sane defaults and support `katex, linkcheck, alerts`
- Remove book building from `build.yml`
Those changes will need to get backported in the next branch. Potentially during the next release.
Waiting to merge it the node before passing this PR as ready for review: https://github.com/0xPolygonMiden/miden-node/pull/748
=> Final changes for mdbook

Cargo.lock, Cargo.toml, crates/miden-lib/asm/miden/note.masm, crates/miden-tx/src/tests/kernel_tests/test_note.rs
This PR adds a padding of values provided to the `compute_inputs_commitment` procedure, making the resulting commitment match the one obtained from the `commitment()` method of the `NoteInputs` structure. 
Closes: #1237
=> Add padding for inputs in `compute_inputs_commitment` procedure

Cargo.lock, bin/proving-service/Cargo.toml, bin/proving-service/src/proxy/health_check.rs, bin/proving-service/src/proxy/update_workers.rs, bin/proving-service/src/utils.rs
part of #1244 
Could not update `opentelemetry` because `tracing-opentelemetry` is not updated yet. The PR in the `tracing-opentelemetry` that uses the new OTel version was merged a couple hours ago, but I don't know when it is going to be released. (https://github.com/tokio-rs/tracing-opentelemetry/pull/196)
=> chore: update axum and tokio in proving service

CHANGELOG.md, crates/miden-objects/src/note/details.rs, crates/miden-objects/src/note/mod.rs, crates/miden-objects/src/transaction/tx_args.rs, crates/miden-tx/src/testing/tx_context/builder.rs, crates/miden-tx/src/tests/mod.rs
The full `NoteDetails` is not necessary for pushing note recipient data to the advice map, so this PR proposes changing the transaction args API. 
I had been thinking of making this change for a while but it makes more sense now, as it's related to https://github.com/0xPolygonMiden/miden-client/issues/470.
Since 0.8 was released already I could rebase this to `main` but was not entirely sure if it was preferred because it's fairly low priority (logic can be copied in the client for now, since it's a concise function anyway). Also it would technically be a breaking change.
=> refactor: Take `AsRef<NoteRecipient>` to extend expected output notes

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/account/delta/storage.rs, crates/miden-objects/src/account/storage/header.rs, crates/miden-objects/src/account/storage/map.rs, crates/miden-objects/src/account/storage/mod.rs, crates/miden-objects/src/errors.rs, crates/miden-tx/src/tests/kernel_tests/test_faucet.rs
Hash keys in `StorageMap` before insertion into SMT.
Adds some missing docs to `StorageMap`, cleans up some names and removes unnecessary (imo) APIs. Also adds a dedicated `StorageMapError` instead of re-exporting `MerkleError`, which has a practical reason. It is inconvenient to call `Smt::with_entries` before building the `BTreeMap`, and calling it afterwards wouldn't catch the duplicates because BTreeMap would have deduplicated them.
closes #1129
=> Hash keys in `StorageMap` before insertion into SMT

CHANGELOG.md, crates/miden-objects/src/batch/proven_batch.rs, crates/miden-objects/src/block/proven_block.rs
Adds a getter to `ProvenBatch` and `ProvenBlock` that returns the security level of the proof.
Currently, it only returns the value of the `MIN_PROOF_SECURITY_LEVEL` constant.
This PR is part of: https://github.com/0xPolygonMiden/miden-node/issues/744
=> feat: add proof security level getter

bin/proving-service/src/commands/worker.rs
Fixes #1265.
I was not able to reproduce this problem on `main` when compiling on release; it only seemed to happen on debug builds. 
This PR removes the short flags so that there are no collisions. The batch prover and block prover flags were also conflicting on `-b` so I removed them as well (and the others for consistency).
For testing these changes you can see that both these commands succeed:
- `cargo run --release -- start-worker --host 0.0.0.0 --port 12324` 
- `cargo run -- start-worker --host 0.0.0.0 --port 12324`
=> refactor: Remove short flags on miden-proving-service

bin/proving-service/README.md
Due to a compilation error in Pingora, updating the transitive dependencies makes the whole binary to fail when compiling. This issue is being address in Pingora, but for the moment using `cargo install miden-proving-service` fails.
Using `cargo install miden-proving-service --locked` is the only way to make the binary work when downloading through crates.io.
=> docs: add comment about transitive dependency error

CHANGELOG.md, bin/proving-service/grafana_dashboard.json, bin/proving-service/src/commands/mod.rs, bin/proving-service/src/commands/proxy.rs, bin/proving-service/src/proxy/health_check.rs, bin/proving-service/src/proxy/metrics.rs, bin/proving-service/src/proxy/mod.rs, bin/proving-service/src/proxy/worker.rs
closes #1009
Also addresses an issue that was causing the workers to be locked for more time than needed when health checking.
=> feat: implement retry strategy for worker health check

crates/miden-objects/README.md
Hi! I fixed multiple broken documentation links in the Miden Objects crate's README, updating them to match the current documentation structure.
=> fix: dead link `miden-objects/README.md`

Cargo.lock, Cargo.toml, bin/proving-service/Cargo.toml
Currently, running `cargo update` updates the `"sfv"` dependency, which is used internally by Pingora. In Pingora, the dependency does not pin any minor version, and in a recent release, the compatibility broke. They are tracking this issue in: https://github.com/cloudflare/pingora/issues/568
While we added a comment about this in main, now that we merged main into next, the lock file was updated and this issue is being reproduced in next too. To allow local development and CI without this compilation errors, patching the dependency works. This is not a definitive solution, given that this version wouldn't work if we want to upload the crate into `crates.io` .
=> fix: temporarily fix pingora

CHANGELOG.md, crates/miden-objects/src/account/code/mod.rs, crates/miden-objects/src/account/code/procedure.rs
Adds pretty print to `AccountCode`.
Since procedures are external, they are printed as:
```
begin
external.<digest>
end
```
Closes #1228
=> feat: pretty print account code

CHANGELOG.md, crates/miden-lib/asm/shared/util/account_id.masm, crates/miden-objects/src/block/account_tree.rs
Small follow-up for the `AccountTree`, addressing this comment: https://github.com/0xPolygonMiden/miden-base/pull/1254#discussion_r2049900789.
Also fixes `compute_mutations` not checking for account ID prefix uniqueness.
In miden-node, this breaks test code in `crates/block-producer/src/test_utils/store.rs` but the fix should be relatively easy cc @Mirko-von-Leipzig.
=> Account Tree follow-up

bin/proving-service/src/commands/mod.rs, bin/proving-service/src/commands/proxy.rs, bin/proving-service/src/commands/update_workers.rs, bin/proving-service/src/commands/worker.rs
Closes #1318 
`cargo check --features clap/deprecated`
Before : 
After Fix :
=> fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(...)]

crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/lib.rs
It seems the re-export was accidentally removed from `miden-tx`. We were using it in `miden-client` to implement the `DataStore` trait (which also needs `MastForestStore`) for our `ClientDataStore`.
=> chore: re-export `MastForestStore`

.github/actions/build_package/action.yml, .github/workflows/package.yml, bin/proving-service/README.md, packaging/prover-proxy/miden-prover-proxy.service, packaging/prover-proxy/postinst, packaging/prover-proxy/postrm, packaging/prover/miden-prover.service, packaging/prover/postinst, packaging/prover/postrm
Adds workflow for building Debian packages for prover and prover-proxy.
Adds systemd service file and install scripts for use in the workflow:
```
packaging
├── prover
│   ├── miden-prover.service
│   ├── postinst
│   └── postrm
└── prover-proxy
├── miden-prover-proxy.service
├── postinst
└── postrm
```
=> chore: Add Debian packaging workflow

.github/actions/build_package/action.yml
Currently the workflow assumes the tagged commit we are packaging includes the Debian packaging files. This will not be the case until we do a Github release including changes from https://github.com/0xMiden/miden-base/pull/1332.
This change will allow us to push the Debian package for v0.8.1 despite the fact that the corresponding commit does not contain the Debian packaging files.
We can revert this change after we do our next Github release.
=> chore: Update Debian package worfklow to work with latest packaging files

.github/workflows/package.yml
The current workflow configuration does not differentiate between AMD64/ARM64 due to the `ubuntu-latest` label being used for both.
=> chore: Fix ARM package workflow runs-on setting

bin/bench-tx/src/main.rs
PR fixes an error in running the `bench-tx` benchmarks for transactions. 
Running `make bench-tx` results in the following error:
```
thread 'main' panicked at bin/bench-tx/src/main.rs:133:10:
called `Result::unwrap()` on an `Err` value: TransactionProgramExecutionFailed(DynamicNodeNotFound(RpoDigest([15598073319142585341, 3746686999150019745, 15192556450201485061, 162899362230949492])))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [bench-tx] Error 101
```
This occurs when benchmarking transactions that consume P2ID notes. See specific function [here](https://github.com/0xMiden/miden-base/blob/2a4b8d18ee1942b328c30460fd1bea97f0e4da9c/bin/bench-tx/src/main.rs#L84)
The [benchmark_p2id](https://github.com/0xMiden/miden-base/blob/2a4b8d18ee1942b328c30 …
=> fix: bench-tx execution

crates/miden-testing/src/mock_chain/account.rs
Continuation of https://github.com/0xMiden/miden-client/pull/890
The `apply_delta` method is used in `MockChain` making the `cfg` unnecessary
=> Remove `dead_code` flag

CHANGELOG.md, crates/miden-lib/src/transaction/inputs.rs, crates/miden-objects/src/asset/mod.rs, crates/miden-objects/src/asset/token_symbol.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/lib.rs
This small PR adds the token symbol length to the resulting encoded token symbol value. This is done to be able to unambiguously decode the underlying symbol string. 
Closes: #1317
=> Update `TokenSymbol` encoding

.github/actions/build_package/action.yml, bin/proving-service/.env, bin/proving-service/README.md, packaging/prover-proxy/miden-prover-proxy.service, packaging/prover-proxy/postinst, packaging/prover-proxy/postrm, packaging/prover/miden-prover.service, packaging/prover/postinst, packaging/prover/postrm
Closes #1341.
Fixes bug that was preventing service and installation files from being included into the packages.
Adds (env var) configuration files for the Debian packages.
Restructures package directories to follow systemd docs:
- `/lib/systemd/system/miden-prover.service`
- `/lib/systemd/system/miden-prover.service.d/debian.conf`
- `/opt/miden-prover/`
=> Refactor Debian packages

clippy.toml, crates/miden-objects/src/account/account_id/mod.rs, crates/miden-objects/src/account/account_id/seed.rs, crates/miden-objects/src/account/account_id/v0/mod.rs, crates/miden-objects/src/batch/proven_batch.rs
Adds the `clippy.toml` file to allow fine-grained configuration of Clippy lints. For example, `disallowed-types` or `doc-valid-idents`.
This PR specifically raises the `too-many-arguments` threshold from 7 to 8, which allows the removal of many `#[allow(clippy::too_many_arguments)]` flags.
=> Add the `clippy.toml` file

Cargo.lock, bin/bench-tx/Cargo.toml, bin/bench-tx/bench-tx.json, bin/bench-tx/src/main.rs, bin/bench-tx/src/utils.rs
Simplifies the benchmarks to avoid some of the awkwardness mentioned in https://github.com/0xMiden/miden-base/pull/1351/files#r2083283082, i.e. using the transaction script twice. This was due to using the transaction context as a data store, when we could've called `TransactionContext::execute` instead - which is what this PR does.
=> Refactor tx benchmark to use `TransactionContext::execute`

Cargo.lock, Cargo.toml, Makefile, bin/proving-service/Cargo.toml, bin/proving-service/README.md, bin/proving-service/src/proxy/mod.rs, bin/proving-service/src/proxy/status.rs
A new Pingora version came out two weeks ago, and includes the fix for the transitive dependency error that we were having (`sfv`). Also updates other dependencies.
Tested it with:
```
cargo publish --dry-run -p miden-proving-service
cargo install --path bin/proving-service --bin miden-proving-service
```
=> chore: update pingora & other deps

crates/miden-objects/src/account/mod.rs
This patch fixes an issue with the 0.9.0 release where `FieldIdentifier` is not exported from `miden-objects`, even though it is present in public APIs of types which are exported, e.g. `WordRepresentation`.
I've made the `miden_objects::account::component` module public here, rather than export just `FieldIdentifier`, as it appears to me that we are largely re-exporting everything from the module anyway in `miden_objects::account`, and rather than further crowd that namespace, this allows one to simply fully-qualify the path to the `FieldIdentifier` type, i.e. `miden_objects::account::component::FieldIdentifier`. Furthermore, if any types are added in this module or its children in the future, which are marked `pub`, there is no risk that we forget to export them. We can use `pub(crate)` …
=> fix(objects): export types used in public apis

.github/actions/build_package/action.yml, .github/workflows/package.yml
Also reinstates previous workflow commands which depended on the released tag containing the package dir contents.
=> chore: Fix Rust version in release workflow

crates/miden-lib/src/account/faucets/mod.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/lib.rs
This tiny PR moves the `FungibleFaucetError` from `miden-objects` to `miden-lib` crate. 
Closes: #1379
=> Move `FungibleFaucetError` from `miden-objects` to `miden-lib`

CHANGELOG.md, crates/miden-objects/src/block/proposed_block.rs, crates/miden-testing/src/kernel_tests/batch/proposed_batch.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs, crates/miden-testing/src/kernel_tests/block/utils.rs
A NOOP transaction is a transaction whose initial and final state commitment are the same. Such transactions can appear in practice for UTXO-like use cases, i.e. where notes are created and consumed but the native account is unchanged.
Before this PR, a block would not be able to contain a NOOP transaction against account A in batch 0 and a state-updating transaction against account A in batch 1. This is because those are technically two transactions that update the same account from the same initial state commitment. This is how a block detects conflicts. However, NOOP transactions should be exempt from this conflict check because they do in fact not change the account, so we can safely ignore such NOOP transactions when aggregating account states. This is what this PR does.
Also adds …
=> Allow NOOP and state-updating transactions in the same block

Cargo.lock
Client integration tests found that there is an incompatibility within `winter-air` versions `0.12.1` and `0.12.3`. 
Currently the node [has it locked to `0.12.3`](https://github.com/0xMiden/miden-node/blob/next/Cargo.lock#L5215), whereas `miden-base` had it locked to `0.12.1`. 
The client integration tests that use the remote proving service were failing at the moment of submitting the proof (execution and proving themselves were fine) to the node, which was outputting errors that looked like this:
```
2025-06-02T15:19:16.216059Z  INFO rpc.rpc/SubmitProvenTransaction:rpc.server.submit_proven_transaction:verify_program: miden_verifier: /Users/igamigo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/miden-verifier-0.14.0/src/lib.rs:55: new rpc.service: "rpc.rpc", rpc.method: …
```
=> chore: refresh winter-air

crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
This small PR implements a new assertion procedure, which checks the correctness of the values stored in the kernel memory section (number of the kernel procedures and their hashes). These values are compared to the ones generated in the `build.rs` and stored in the `TransactionKernel`.
Closes: #884
=> Prologue test for kernel section

docs/src/account.md
This commit enhances the docs/src/account.md documentation by adding a comprehensive subsection about StorageMap under the Storage section. The new content explains the structure and properties of StorageMap, including its implementation as a sparse Merkle tree (SMT), the use of key hashing for efficiency, support for partial presence of entries during transaction execution, and the retention of original keys for introspection. All information is based strictly on the project's codebase and referenced comments, addressing the requirements of issue #1213 and related discussions. No speculative or invented details were included.
=> Add detailed StorageMap documentation to account section

crates/miden-testing/src/tx_context/builder.rs
This PR adds a function to set `NoteArgs` when using the `TransactionContextBuilder`. It is possible that I am missing something, but I couldn't find anywhere in the tests that use the `MockChain` where `NoteArgs` are set. 
This PR enables the ability to set `NoteArgs` for the notes that are being consumed when using the `MockChain`.
=> feat: add note_args to TransactionContextBuilder

crates/miden-lib/asm/kernels/transaction/api.masm, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
This small PR implements two new procedures in the `account.masm`: `add_asset_to_account_vault` and `remove_asset_from_account_vault`. These procedures are wrappers around `add_asset` and `remove_asset` asset vault procedures — this will allow us to maintain the account vault exclusively, making possible to move the corresponding events from the `api.masm` to `account.masm` file.
Closes: #1089.
=> Move account vault events from `api.masm` to `account.masm`

crates/miden-lib/asm/kernels/transaction/api.masm, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/miden/account.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/note/assets.rs, crates/miden-objects/src/testing/account_code.rs, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs
- Fixes outdated `account::set_item` docs, removing the reference to the "new storage commitment" which is no longer returned.
- Uses proper variable names instead of single-letter names. (Could needs a larger refactor to do this everywhere).
- Fixes outdated docs that at least one asset is required in a note.
=> Fix outdated `account::set_item` docs

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/src/errors/tx_kernel_errors.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/transaction/proven_tx.rs, crates/miden-testing/src/kernel_tests/block/proven_block_error.rs, crates/miden-testing/src/kernel_tests/block/utils.rs, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_epilogue.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, docs/src/transaction.md
This PR adds two additional checks to make sure that the executed transaction is not empty, i.e. changes the account state or consumes at least one note. This check was added into the kernel's `epilogue` and into the `ProvenTransaction::validate`.
Closes: #1402.
=> Forbid empty transactions

crates/miden-lib/src/account/interface/test.rs, crates/miden-objects/src/testing/account_component.rs, crates/miden-testing/src/kernel_tests/mod.rs
Simplify named module assembly by using `NamedSource` instead of the `ModuleParser` as suggested in https://github.com/0xMiden/miden-vm/issues/1673.
=> Simplify named module assembly

CHANGELOG.md, crates/miden-objects/src/constants.rs
This PR changes the `ACCOUNT_UPDATE_MAX_SIZE` from 32 KiB to 256 KiB to allow for testing of accounts that were compiled using the Rust to Miden assembly compiler. 
This is a temporary change to allow for testing. `ACCOUNT_UPDATE_MAX_SIZE` should be set back to 32 KiB once MASM produced by the compiler becomes more optimized.
Resolves #1441
=> Temporarily bump ACCOUNT_UPDATE_MAX_SIZE to 256 KiB

CHANGELOG.md, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/tx_context/context.rs, crates/miden-tx/src/auth/tx_authenticator.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/executor/notes_checker.rs, crates/miden-tx/src/host/mod.rs, crates/miden-tx/src/prover/mod.rs
This PR replaces `Arc<dyn DataStore` with a normal reference `&'a dyn DataStore`.
Existing `Arc<DataStore` types will somewhat automatically gain `'a = 'static` and shouldn't be inconvenienced more than doing `x.as_ref()` in the constructor (if needed at all).
I'm uncertain if this still enables the original motivation for using `Arc`. Tests and lints pass.. :shrug: 
I want this so I can use my `DataStore` in a single threaded context. Note that there is also `Option<Arc<dyn TransactionAuthenticator>>` however in my usage this is always `None`. If desired, I can also change this to a reference? --edit-- new commit makes this change as well.
=> feat: remove Arc from tx executor

CHANGELOG.md, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/mod.rs, crates/miden-tx/src/host/script_mast_forest_store.rs, crates/miden-tx/src/prover/mod.rs
Close #1452 
This PR introduces the following changes:
- Load account and input notes advice maps into the advice provider before executing them;
- `TransactionHost::new` now expects `&Account` instead `AccountHeader`.
I tried to test these changes by pulling them through the `miden-client` (next branch, `v0.10`) and patching numerous deps along the way to try it in the test reproduced in #1452 but stumbled upon testnet node rejecting my request because my client is not `v0.9`. So, no luck. 
Next, I looked into `miden-testing` to introduce a test there, but found that it'd take quite a lot of efforts to construct a proper test case (a note script, loading the data from the advice provider and calling an account that is also loads another data from the advice provider). OTOH, the code …
=> fix: load account and input notes advice maps into the advice provider before executing them

crates/miden-lib/asm/kernels/transaction/lib/account.masm
Fixed the order in comment, and split the ops across two lines for clarity
=> fix: Order of `proc_ptr`, `metadata_ptr` in account kernel comment

CHANGELOG.md, crates/miden-lib/src/transaction/inputs.rs, crates/miden-lib/src/transaction/mod.rs, crates/miden-objects/src/transaction/tx_args.rs
I think the last few commits in https://github.com/0xMiden/miden-base/pull/1425 refactored a few functions so that we don't need to return `Result<>` anymore. This PR adds this change, as well as a smaller one that gates a mutator behind the `testing` feature.
=> refactor: Change return type in advice inputs constructor

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/memory.rs, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/account/delta/mod.rs, crates/miden-objects/src/account/delta/vault.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
Implement fungible asset vault in-kernel account delta.
The high-level approach is that the fungible asset delta is kept track of using the following layout of a value in a link map: `[amount_hi, amount_lo, faucet_id_suffix, faucet_id_prefix]` where `amount_hi` and `amount_lo` are the u32 limbs of the amount delta by which the fungible asset's amount has changed.
In the `account::add_fungible_asset` and `account::remove_fungible_asset` procedures, we call analogous functions in `account_delta` that update the link map. When computing the delta, all entries that zero out (e.g. asset amount 100 added and 100 removed) are ignored and not hashed into the delta commitment.
When the delta is computed, the above representation is converted to the regular fungible asset representation prepended …
=> Implement in-kernel account delta for fungible assets

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/account/delta/vault.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
Implement in-kernel account delta for non fungible assets.
The approach is very similar to the fungible asset delta in #1460. See `account_delta::add_non_fungible_asset` for documentation on the link map layout used to bookkeep the changed assets.
part of #1198
=> Implement in-kernel account delta for non fungible assets

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/memory.rs, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/account/delta/mod.rs, crates/miden-objects/src/account/delta/storage.rs, crates/miden-objects/src/account/storage/map.rs, crates/miden-objects/src/transaction/proven_tx.rs, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-tx/src/host/link_map.rs, crates/miden-tx/src/host/mod.rs
Implement in-kernel account delta for storage maps.
Main Changes:
- Use `LexicographicWord` in `StorageMapDelta` to sort keys in the storage map deltas in the same way in Rust and in-kernel.
- Don't insert a key-value pair into the storage map delta if prev_value == new_value, which normalizes account deltas in the simplest case. This is addressed more holistically in #1496.
- Implement storage map deltas.
- Update delta commitment hasher state with changed storage map entries.
part of #1198
=> Implement in-kernel account delta for storage maps

CHANGELOG.md, crates/miden-lib/src/transaction/memory.rs, crates/miden-objects/src/account/delta/mod.rs, crates/miden-objects/src/account/delta/storage.rs, crates/miden-objects/src/account/delta/vault.rs, crates/miden-objects/src/account/mod.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/transaction/proven_tx.rs, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-testing/tests/integration/scripts/faucet.rs, crates/miden-tx/src/errors/mod.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/account_delta_tracker.rs
Refactor account delta nonce from `Option<Felt>` to `Felt`.
Previously (I think) `None` was used to represent "nonce has not changed" but since the nonce was changed to represent the increment of the nonce rather than its absolute new value in #1404, this is no longer necessary now and `0` can be used to represent "no change" instead.
Also removes an unused `From<Account> for AccountDelta` implementation, though if we still need this, that commit can be easily reverted. I don't think this should really be necessary since deltas are created in the transaction executor, but cc @igamigo in case you need this in the client.
part of #1198
=> Refactor account delta nonce from `Option<Felt>` to `Felt`

crates/miden-tx/src/lib.rs
Looks like (probably while solving merge conflicts) I might have [accidentally removed](https://github.com/0xMiden/miden-base/pull/1518/files#diff-8425b256bd1459318a47d96a5eb74e5e8e0482dc657c56b144cdc9abf66b9962R13) a re-export originally introduced [here](https://github.com/0xMiden/miden-base/pull/1502/files#diff-8425b256bd1459318a47d96a5eb74e5e8e0482dc657c56b144cdc9abf66b9962R13). This PR re-adds it.
=> fix: Re-add `ExecutionOptions` re-export

crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
=> Introduce `get_acct_procedure_ptr` method in `miden::memory`

CHANGELOG.md, Makefile, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/errors/tx_kernel_errors.rs, crates/miden-objects/src/account/delta/mod.rs, crates/miden-objects/src/account/mod.rs, crates/miden-testing/src/kernel_tests/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-testing/src/kernel_tests/tx/test_prologue.rs, crates/miden-testing/src/utils.rs, crates/miden-testing/tests/integration/scripts/faucet.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/account_delta_tracker.rs, crates/miden-tx/src/host/mod.rs
Define the commitment to an empty account delta as `EMPTY_WORD`.
This assumes that `account_delta::compute_commitment` is only called when no more changes to the delta will be made. Otherwise, using `nonce_increment == 0` as an indicator for an empty delta is not good enough (see https://github.com/0xMiden/miden-base/issues/1522#issuecomment-3034831973).
Ideally, we'd have a concept of sealing the transaction, i.e. a point after which no more changes can be made. Before the transaction is sealed, calling `compute_commitment` would fail, so it could only be called afterward (most likely by an auth procedure after it has incremented the nonce).
Misc changes:
- Removed the TODO for adding a delta commitment test called from foreign accounts, because due to the above, this scenario might …
=> Define the commitment to an empty account delta as `EMPTY_WORD`

crates/miden-lib/src/lib.rs
Removes an erroneous `#[cfg(any(feature = "testing", test))]`. That should have been on the `errors` below probably but that was actually changed in #1507 to only gate the tx kernel and note script errors within the errors module.
closes #1552
=> chore: Remove erroneous `#[cfg(any(feature = "testing", test))]`

CHANGELOG.md, crates/miden-lib/src/transaction/inputs.rs, crates/miden-objects/src/block/nullifier_tree.rs, crates/miden-objects/src/block/partial_nullifier_tree.rs, crates/miden-objects/src/block/proposed_block.rs, crates/miden-objects/src/note/header.rs, crates/miden-objects/src/note/note_id.rs, crates/miden-objects/src/note/nullifier.rs, crates/miden-objects/src/transaction/inputs/notes.rs, crates/miden-objects/src/transaction/transaction_id.rs, crates/miden-testing/src/kernel_tests/tx/test_prologue.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/tx_context/context.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/mod.rs, crates/miden-tx/src/host/script_mast_forest_store.rs, crates/miden-tx/src/prover/mod.rs
VM Migration follow-up:
- Rename `ScriptMastForestStore::advice_data` -> `advice_map` which is more precise.
- Rename `{TransactionId, NoteId, Nullifier}::inner` -> `as_word`.
- Rename `TransactionAdviceInputs::into_inner` -> `into_advice_inputs`.
=> chore: rename `inner` functions to be more precise

crates/miden-tx/Cargo.toml
This PR adds a small change to the `async` feature in `miden-tx` which was not building correctly.
I don't get why it didn't pop up in the `make build-async` command but the error can be replicated in `next` by only building that package with the command `cargo build --release --features async -p miden-tx`. Should I add this check to the makefile so it is used in the CI? It does seem a bit ad-hoc and like it should be covered by `make build-async`.
This will also return other errors which are related to the use of the `testing` feature, I couldn't find an easy fix for this so I'll be creating a [separate issue](https://github.com/0xMiden/miden-base/issues/1588) but it is currently non-blocking for updating the client and node (we can temporarily use the `testing` feature when building …
=> fix: use async for miden-prover

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/asm/kernels/transaction/lib/prologue.masm, crates/miden-lib/src/transaction/inputs.rs, crates/miden-lib/src/transaction/memory.rs, crates/miden-objects/src/testing/account_component.rs, crates/miden-objects/src/transaction/tx_args.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs, crates/miden-testing/src/kernel_tests/block/utils.rs, crates/miden-testing/src/kernel_tests/tx/mod.rs, crates/miden-testing/src/kernel_tests/tx/test_auth.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/mock_chain/auth.rs, crates/miden-testing/src/tx_context/builder.rs
Pass authentication arguments to the auth component:
- similar to how tx arguments are passed, but we don't need to add TX_SCRIPT_ROOT to the advice stack (it's already there via loading account procedures)
- allow tx builder to specify these arguments
closes https://github.com/0xMiden/miden-base/issues/1579
=> Auth procedure arguments

crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
instead of `padw mem_loadw` and some sequence of `drop / swap`s, we can use `mem_load` directly
closes #1132
=> chore: optimize `mem_loadw` -> `mem_load` when possible

CHANGELOG.md, crates/miden-objects/src/block/account_tree.rs
In https://github.com/0xMiden/miden-node/pull/1094 we need a way to check whether an account Id's prefix is present in the `AccountTree`.
- Add `AccountTree::contains_account_id_prefix()` and  `AccountTree::id_prefix_to_smt_key()`.
- Add unit test showing duplicate prefixes cause collision.
=> feat: Add fn to check Account Id prefix existence in AccountTree

Cargo.toml
part of https://github.com/0xMiden/miden-node/pull/1093
The update was already introduced in the `Cargo.lock`.
=> chore: update miden-vm version in `Cargo.toml`

CHANGELOG.md, crates/miden-lib/asm/miden/contracts/auth/basic.masm, crates/miden-lib/src/transaction/events.rs, crates/miden-tx/src/executor/exec_host.rs, crates/miden-tx/src/host/mod.rs
Rename `TransactionEvent::FalconSigToStack` to `TransactionEvent::AuthRequest`.
Note: I went with `AuthRequest` instead of `AuthRequested` since most event names use present tense (but it's not consistent, so up for discussion).
I'll do the arbitrary signature event in another PR since it should probably build on top of https://github.com/0xMiden/miden-base/pull/1616.
part of https://github.com/0xMiden/miden-base/issues/1593
=> chore: rename `TransactionEvent::FalconSigToStack` to `TransactionEvent::AuthRequest`

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/asm/kernels/transaction/lib/prologue.masm, crates/miden-lib/asm/kernels/transaction/main.masm, crates/miden-lib/src/transaction/inputs.rs, crates/miden-lib/src/transaction/memory.rs, crates/miden-objects/src/transaction/tx_args.rs, crates/miden-objects/src/transaction/tx_witness.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/tx_context/builder.rs
This small PR renames different "versions" of the transaction script arguments name used across the repo. 
The only version we want to use is `tx_script_args`/`TX_SCRIPT_ARGS`. Comments were also updated to use the full `transaction script arguments` version.
Closes: #1578.
=> Make transaction script arguments name consistent 

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/src/errors/note_script_errors.rs, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/testing/account_component.rs, crates/miden-testing/src/kernel_tests/tx/test_auth.rs
closes #1503
Uses the tracked procedures to figure out if, right before invoking the auth procedure of the account, the auth procedure has already been called or not.
It also fixes the lack of tracking for the auth procedure, similar to how "normal" account procedures are tracked in `authenticate_and_track_procedure`.
=> feat: auth procedure should only be called from epilogue

CHANGELOG.md, crates/miden-lib/asm/miden/contracts/auth/basic.masm, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-tx/src/host/mod.rs
Extract `TransactionSummary` in stack order in `TransactionBaseHost::on_unauthorized`.
Makes `::miden::contracts::auth::basic::{create_tx_summary, hash_tx_summary}` public, since they may be useful for other uses and it enables calling this procedure in tests.
Updates the existing test to make use of `compute_delta_commitment` which is now available.
This matches the way the summary is constructed in the VM to avoid having to rearrange the words on the stack.
This came out of https://github.com/0xMiden/miden-base/pull/1624 and builds on top of that and another PR.
=> feat: extract `TransactionSummary` in stack order

CHANGELOG.md, crates/miden-objects/src/transaction/partial_blockchain.rs
We are updating Ntx Builder state to track chain tip via `PartialBlockchain`: https://github.com/0xMiden/miden-node/pull/1108.
The partial chain is pruned in order limit memory consumption and performance hit of clones. The ability to know the number of blocks tracked by the partial chain would help reduce logic in the Ntx builder stack.
- Add `PartialBlockchain::num_tracked_blocks()`.
- Update prune unit test to validate new fn works as expected.
=> feat: Add PartialBlockchain::num_tracked_blocks()

CHANGELOG.md, Cargo.lock, crates/miden-objects/src/block/account_tree.rs, crates/miden-objects/src/block/blockchain.rs, crates/miden-objects/src/block/nullifier_tree.rs, crates/miden-testing/src/mock_chain/chain.rs, crates/miden-testing/src/mock_chain/note.rs, crates/miden-tx/src/auth/tx_authenticator.rs
This PR implements serialization for `MockChain`. This is needed for [this miden-client issue](https://github.com/0xMiden/miden-client/issues/1064) where users want a way to persist a `MockChain` (among other things).
This PR depends on a [this separate `miden-crypto` PR](https://github.com/0xMiden/crypto/pull/466) that implements serialization for `Mmr`.
=> feat: implement serialization for `MockChain`

crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/src/errors/tx_kernel_errors.rs
I'm not sure about putting URLs into the error message, but in any case the doc aren't there yet to link against (but we could reference [docs/src/account/code.md#Authentication](https://github.com/0xMiden/miden-base/pull/1523/files#diff-80b077c708d8bbc3d399da4d65af90159e107ea453cb533925e1032fb5ebc9a5) once that PR is ready)
closes #1644
=> chore: make `ERR_ACCOUNT_PROC_NOT_AUTH_PROC` more verbose

CHANGELOG.md, crates/miden-lib/asm/miden/contracts/auth/basic.masm, crates/miden-lib/src/errors/transaction_errors.rs, crates/miden-tx/src/executor/exec_host.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/mod.rs
builds on https://github.com/0xMiden/miden-base/pull/1615 and https://github.com/0xMiden/miden-base/pull/1616, and by extension https://github.com/0xMiden/miden-base/pull/1596.
requires some changes to `basic.masm` to work, but since we are changing the message to be signed as part of https://github.com/0xMiden/miden-base/issues/1534, I haven't touched that part yet. Basically, the emit event expects this to be the stack now:
```
emit.FALCON_SIG_TO_STACK
exec.rpo_falcon512::verify
dropw dropw dropw dropw
```
(the stack words can be rearranged for efficiency if needed)
blocked by #1534
=> feat: Pass `SignatureData` to `TransactionAuthenticator`; no more blind signing

CHANGELOG.md, crates/miden-lib/src/account/faucets/mod.rs, crates/miden-objects/src/errors.rs, crates/miden-testing/tests/scripts/faucet.rs
This was proposed in https://github.com/0xMiden/miden-faucet/pull/30#discussion_r2238035374
This PR adds a `FungibleFaucetExt` trait that provides methods to access the faucet issuance from the storage.
=> feat: add faucet storage accessors

CHANGELOG.md, bin/bench-tx/bench-tx.json, bin/bench-tx/src/main.rs, bin/bench-tx/src/utils.rs, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/asm/kernels/transaction/lib/link_map.masm, crates/miden-lib/asm/kernels/transaction/main.masm, crates/miden-lib/src/transaction/events.rs, crates/miden-lib/src/transaction/procedures/kernel_v0.rs, crates/miden-objects/src/transaction/executed_tx.rs, crates/miden-tx/src/host/mod.rs, crates/miden-tx/src/host/tx_progress.rs
Implements a basic `compute_fee` procedure in the tx kernel epilogue.
This builds on top of #1652.
Most of the PR is actually about updating the `TransactionProgress` and `TransactionMeasurements` (and fixing the tx benchmark) to get an estimation for how long the epilogue takes after `clk` in `compute_fee` was called. This is a crude estimation and will most likely have to be corrected up when we start testing this. The estimation is a hardcoded value and does not take into account the variable length of account storage and code or the number of input and output notes, which affect the cycle count.
It would be ideal if we could _calculate_ the number of cycles all procedures after `compute_fee` in the epilogue take, by providing inputs like storage size, number of account procedures and …
=> feat: Implement `compute_fee`

.github/workflows/release-plz.yml
cherry-picked 83b4e5d from `next` to `main` so that the release CI job can be automated
=> chore: Fix release-plz workflow (#1558)

.github/workflows/build.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, bin/bench-prover/src/bench_functions.rs, crates/miden-testing/Cargo.toml, crates/miden-testing/src/tx_context/context.rs, crates/miden-testing/tests/lib.rs, crates/miden-tx/Cargo.toml, crates/miden-tx/src/executor/data_store.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/executor/notes_checker.rs, crates/miden-tx/src/lib.rs, crates/miden-tx/src/prover/mod.rs
~Does not compile yet, since it calls
`fn prove` from `miden-vm`, which in turn uses the provers in `winterfell-prover` which also use `#[maybe_async]` which resolves to `#[async_trait(?Send)]`~
~Possibly requires: https://github.com/0xMiden/miden-vm/pull/2044~
Changes:
*  Add extra bounds to two instances of `Arc<dyn SourceManager>` -> `Arc<dyn SourceManager +Send + Sync>` -> this might go away with a refactor which is out of scope for this PR
* `fn prove` becomes async
* Delete `trait TransactionProver`
* Avoid any usage of `#[maybe_async]`, which does not enforce `+ Send` requirements for a multithreaded executor
* Remove "async" feature
* Delete dead CI target
* Delete makefile target
=> delete trait `TransactionProver`, avoid `#[maybe_async]`

crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
Optimizes the storage delta computation by using `neq` instead of `lt`.
The original idea in https://github.com/0xMiden/miden-base/issues/1509 was to use `mem_stream` in `update_storage_delta`, but I don't think that works as intended. `mem_stream` overwrites the `RATE` words directly, but we cannot overwrite them until we have computed whether the value slot has actually changed. If it hasn't changed, we need to keep the original RATE words.
So we could only use `mem_stream` in `update_value_slot_delta`, but even here we first load the current and initial item, compare them and _then_ overwrite the RATE words. We could use `mem_stream` for loading them, so instead of `account::get_item` and `get_item_initial`, but we would only save a few cycles for not having to compute the `slot_ptr` …
=> chore: optimize storage delta commitment computation

CHANGELOG.md, bin/bench-tx/src/main.rs, crates/miden-lib/src/account/interface/mod.rs, crates/miden-lib/src/account/interface/test.rs, crates/miden-lib/src/utils/script_builder.rs, crates/miden-objects/src/note/script.rs, crates/miden-objects/src/transaction/tx_args.rs, crates/miden-testing/src/kernel_tests/block/utils.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-testing/src/kernel_tests/tx/test_auth.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, crates/miden-testing/src/kernel_tests/tx/test_input_note.rs, crates/miden-testing/src/kernel_tests/tx/test_note.rs, crates/miden-testing/src/kernel_tests/tx/test_output_note.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/tests/auth/rpo_falcon_procedure_acl.rs, crates/miden-testing/tests/lib.rs, crates/miden-testing/tests/scripts/faucet.rs, crates/miden-testing/tests/scripts/p2id.rs, crates/miden-testing/tests/scripts/send_note.rs, crates/miden-testing/tests/scripts/swap.rs
This PR addresses #1568 to use the `ScriptBuilder` `compile_note_script` and `compile_tx_script` methods instead of `{TransactionScript, NoteScript}::compile` which requires us to pass in an assembler. 
There were some tests that use a custom assembler which could not use the `ScriptBuilder` because the `ScriptBuilder` uses the standard `TransactionKernel::assembler()` assembler.
=> Removed `TransactionScript::compile` & `NoteScript::compile` methods in favor of `ScriptBuilder`

CHANGELOG.md, crates/miden-lib/src/account/interface/test.rs, crates/miden-lib/src/transaction/mod.rs, crates/miden-lib/src/utils/script_builder.rs, crates/miden-testing/src/executor.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-testing/src/kernel_tests/tx/test_account_interface.rs, crates/miden-testing/src/kernel_tests/tx/test_asset_vault.rs, crates/miden-testing/src/kernel_tests/tx/test_epilogue.rs, crates/miden-testing/src/kernel_tests/tx/test_faucet.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, crates/miden-testing/src/kernel_tests/tx/test_input_note.rs, crates/miden-testing/src/kernel_tests/tx/test_note.rs, crates/miden-testing/src/kernel_tests/tx/test_output_note.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/tx_context/builder.rs, crates/miden-testing/src/tx_context/context.rs, crates/miden-testing/src/utils.rs, crates/miden-testing/tests/auth/rpo_falcon_acl.rs, crates/miden-testing/tests/scripts/send_note.rs
Follow-up to https://github.com/0xMiden/miden-base/pull/1732 to rename the kernel and script builder APIs to be consistent with each other and to capture the fact that multiple mock libraries are now involved.
Also removes `ScriptBuilder::with_kernel_library`, which we don't actually need. This builder is used to assemble note and tx scripts, but those can never legally use the kernel library directly, they have to call kernel procedures, and so all of those could actually be replaced with `ScriptBuilder::default`.
The interesting parts of this PR are in `crates/miden-lib/src/transaction/mod.rs` and `crates/miden-lib/src/utils/script_builder.rs`.
=> chore: rename mock library apis on `TransactionKernel` and `ScriptBuilder`

CHANGELOG.md, crates/miden-objects/src/address/mod.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/lib.rs, crates/miden-objects/src/note/mod.rs, crates/miden-objects/src/note/note_tag.rs
Add `Address` and `AccountIdAddress` types.
Enable `NoteTag` derivation from `Address` with configurable tag length.
For now, we're skipping the fields `encryption_key` and `interface` from the issue https://github.com/0xMiden/miden-base/issues/1454.
For now I decided not to include `Network` accounts - these will not have public keys, so I'm not sure whether `Address` makes sense. If anything, then for consistency we could just make `Address` simply wrap the `AccountId` with pub_key as `None` and `tag_len` always set to 30.
This is just the first step, with no breaking change here in miden-base, and I don't think (?) there will be any. For example, protocol level methods such as `create_p2ide_note` etc. which currently take `AccountId`, should continue to operate the same.
Most changes …
=> Introduce `Address` struct

crates/miden-lib/asm/account_components/no_auth.masm, crates/miden-lib/asm/account_components/rpo_falcon_512_acl.masm, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
This small PR resolves a `TODO` comment in the epilogue. Updated to use `word::eqz` as opposed to `padw eqw`.
Adds https://github.com/0xMiden/miden-vm/issues/1483 to miden-base
There are most likely other areas in miden-base that could use `word::eqz`.
=> use `std::word` for word equality checks

CHANGELOG.md, crates/miden-testing/src/kernel_tests/tx/test_fee.rs, crates/miden-tx/src/errors/mod.rs, crates/miden-tx/src/executor/exec_host.rs, crates/miden-tx/src/executor/mod.rs
Fixes #1772 
- Adds new variant `TransactionExecutionError::InsufficientFunds`
- Returns this error in `on_tx_fee_computed`
- update test to check correct error
Note: Should we remove the `TransactionKernelError::InsufficientFunds` variant?
=> feat: add `TransactionExecutorError::InsufficientFee`

CHANGELOG.md, crates/miden-objects/src/account/account_id/mod.rs, crates/miden-objects/src/account/account_id/network_id.rs, crates/miden-objects/src/account/mod.rs, crates/miden-objects/src/address/mod.rs
Fixes #1758
One downside of this is `NetworkID` no longer derives `Copy` trait
=> feat: remove bech32 types from public NetworkID

CHANGELOG.md, crates/miden-lib/src/account/interface/mod.rs, crates/miden-objects/src/account/account_id/id_prefix.rs, crates/miden-objects/src/account/account_id/mod.rs, crates/miden-objects/src/account/account_id/storage_mode.rs, crates/miden-objects/src/account/mod.rs, crates/miden-objects/src/block/block_account_update.rs, crates/miden-objects/src/errors.rs, crates/miden-objects/src/note/note_tag.rs, crates/miden-objects/src/transaction/proven_tx.rs, crates/miden-tx/src/prover/mod.rs
Rename the `is_onchain` method to `has_public_state` for `AccountId`, `AccountIdPrefix`, `Account`, `AccountInterface` and `AccountStorageMode`, as discussed here: https://github.com/0xMiden/miden-base/pull/1840#discussion_r2317925648.
Note that we use on-chain fairly pervasively in docs, but I think the remaining occurrences are clear enough.
=> chore: rename `is_onchain` to `has_public_state`

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/src/transaction/events.rs, crates/miden-objects/src/asset/vault/asset_witness.rs, crates/miden-testing/src/kernel_tests/tx/test_lazy_loading.rs, crates/miden-tx/src/executor/exec_host.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/mod.rs
Loads the initial native asset of the native account lazily and removes the assumption that the partial vault tracks all assets of the account.
While working on lazy storage map item loading, tests were failing under certain conditions when lazy loading was enabled, so it had to be done now.
This currently always goes to the data store to fetch the initial state of the asset. Ideally, there would be a way to check the advice provider first and only go to the store if it's not present, but I'm not sure how to do it.
closes https://github.com/0xMiden/miden-base/issues/1754
=> feat: load the initial fee asset lazily

crates/miden-tx/src/prover/mod.rs
Apply changes from #1866 to `next` where the `test_nested_fpi_cyclic_invocation` is currently failing.
=> chore: apply changes from 1866 to next

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/api.masm, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/src/transaction/events.rs, crates/miden-lib/src/transaction/inputs.rs, crates/miden-lib/src/transaction/kernel_procedures.rs, crates/miden-objects/src/transaction/executed_tx.rs, crates/miden-objects/src/transaction/tx_witness.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, crates/miden-testing/src/kernel_tests/tx/test_lazy_loading.rs, crates/miden-testing/src/mock_host.rs, crates/miden-testing/src/tx_context/builder.rs, crates/miden-testing/src/tx_context/context.rs, crates/miden-tx/src/errors/mod.rs, crates/miden-tx/src/executor/data_store.rs, crates/miden-tx/src/executor/exec_host.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/host/account_procedures.rs, crates/miden-tx/src/host/mod.rs, crates/miden-tx/src/host/script_mast_forest_store.rs, crates/miden-tx/src/prover/mod.rs, crates/miden-tx/src/prover/prover_host.rs
This PR implements lazy loading for foreign accounts.
Essentially, foreign accounts do no longer have to be passed into the transaction ahead of time (via `TransactionArgs::new(..., foreign_account_inputs)`). Note that we cannot remove this parameter just yet due to https://github.com/0xMiden/miden-base/issues/1872. Instead, for those cases where lazy loading can be enabled, they are loaded on demand when the first `tx_start_foreign_context` call is made for a foreign account.
This resulted in the following changes:
- Introduced an event `ACCOUNT_BEFORE_LOAD` to signal that an account is being loaded.
- I moved account loading from `tx_start_foreign_context` to `account::load_from_advice`. The main motivation for this PR is to keep all account-related events defined in `account.masm` …
=> feat: load foreign accounts lazily on first access

CHANGELOG.md, Cargo.lock, crates/miden-block-prover/Cargo.toml, crates/miden-lib/Cargo.toml, crates/miden-objects/Cargo.toml, crates/miden-testing/Cargo.toml, crates/miden-tx-batch-prover/Cargo.toml, crates/miden-tx/Cargo.toml, crates/miden-tx/src/auth/tx_authenticator.rs
To enable the wallet to display the full message before signing, we need {de}serialization of `SigningInputs`: https://github.com/0xMiden/miden-base/pull/1858
=> chore: patch v0.11.3

docs/src/SUMMARY.md, docs/src/asset.md, docs/src/fees.md, docs/src/transaction.md
Add docs/src/fees.md explaining automatic fee computation, native asset payment, and outputs, with code citations.
Link Fees page in docs/src/SUMMARY.md.
Correct docs/src/asset.md to state fees are paid in the native asset.
Update docs/src/transaction.md epilogue to mention automatic fee deduction and link to Fees.
Refs #1683.
=> docs: add Fees section and align docs with kernel fee logic

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm, crates/miden-lib/asm/kernels/transaction/lib/link_map.masm, crates/miden-lib/asm/kernels/transaction/lib/output_note.masm, crates/miden-lib/src/transaction/kernel_procedures.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_epilogue.rs, crates/miden-testing/src/kernel_tests/tx/test_link_map.rs
This PR replaces all usages of `eqw` instruction with `exec.word::test_eq` or `exec.word::eq` procedure execution. 
It also removes `is_key_greater` and `is_key_less` helper procedures from the `link_map` kernel module, replacing their usages with the `exec.word::gt` and `exec.word::lt` procedure executions.
Closes: #1658.
=> Replace word functionality with `std::word` procedures

CHANGELOG.md, crates/miden-lib/asm/kernels/transaction/api.masm, crates/miden-lib/asm/kernels/transaction/lib/account.masm, crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm, crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/asm/miden/account.masm, crates/miden-lib/asm/miden/kernel_proc_offsets.masm, crates/miden-lib/src/testing/mock_account_code.rs, crates/miden-lib/src/transaction/kernel_procedures.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, docs/src/protocol_library.md
This PR adds two new kernel procedures:
* `account::get_item_init`
* `account::get_map_item_init`
Additionally this PR adds three tests to test the functionality of the kernel procedures listed above.
Tests:
1. `test_get_item_init`: tests that `get_item_init` procedure returns the initial storage slot value.
2. `test_get_map_item_init`: tests that `get_map_item_init` procedure returns initial map values.
3. `test_get_item_init_and_get_map_item_init_with_foreign_account`: tests `get_item_init` & `get_map_item_init` in the contex of a FPI call. 
Resolves: #1880
=> Add initial slot & map storage kernel procedures

CHANGELOG.md, crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs, crates/miden-testing/src/kernel_tests/tx/test_account_interface.rs, crates/miden-testing/src/kernel_tests/tx/test_fee.rs, crates/miden-testing/src/kernel_tests/tx/test_note.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/mock_chain/chain_builder.rs, crates/miden-testing/src/tx_context/builder.rs, crates/miden-testing/tests/auth/rpo_falcon_acl.rs, crates/miden-testing/tests/scripts/faucet.rs, crates/miden-testing/tests/scripts/swap.rs
=> feat: Rename MockChainBuilder::add_note to add_output_note

CHANGELOG.md, crates/miden-lib/asm/account_components/multisig_rpo_falcon_512.masm, crates/miden-lib/asm/miden/auth/rpo_falcon512.masm, crates/miden-testing/src/kernel_tests/tx/test_account_interface.rs, crates/miden-testing/tests/auth/multisig.rs, crates/miden-testing/tests/auth/rpo_falcon_acl.rs, crates/miden-tx/src/errors/mod.rs, crates/miden-tx/src/executor/mod.rs, crates/miden-tx/src/executor/notes_checker.rs, crates/miden-tx/src/lib.rs
This PR adds a new `check_note_consumability_without_signatures` method to the `NoteConsumptionChecker`, which checks whether the provided note could be consumed by the provided account by executing the transaction.
This method then checks the result of the transaction: it's capable of determine whether the transaction failed because of the authorization error.
TODO list for the follow up PRs:
- Add static checks for the well-known notes.
- Add more granularity to the handling of the errors which were raised from the epilogue (handle the insufficient fee case and so on).
Closes: #1881
=> Auth considerated consumption checker

crates/miden-lib/src/auth.rs, crates/miden-lib/src/testing/account_interface.rs
Resolves #1953
Adds a `get_public_key_commitments` method to `AuthScheme`:
```rs
impl AuthScheme {
pub fn get_public_key_commitments(&self) -> Vec<Word> {
// returns all public keys in Word form
}
}
```
=> feat: add `get_public_key_commitments` method to `AuthScheme` #1953

CHANGELOG.md, Cargo.lock, crates/miden-lib/Cargo.toml, crates/miden-lib/asm/account_components/multisig_rpo_falcon_512.masm, crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm, crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm, crates/miden-lib/asm/kernels/transaction/main.masm, crates/miden-lib/asm/miden/auth/rpo_falcon512.masm, crates/miden-lib/build.rs, crates/miden-lib/src/transaction/events.rs, crates/miden-objects/src/block/account_witness.rs, crates/miden-objects/src/block/partial_account_tree.rs, crates/miden-objects/src/transaction/inputs/account.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/mock_host.rs, crates/miden-tx/src/host/mod.rs
Closes #1950
* Dynamically constructs the constants for the `TransactionEvent` based on masm file `const.X=event("foo::bar")"` definitions
* `AccountWitness` uses the `SparseMerklePath` impl
* unify MASM event const names to have an `_EVENT` suffix, the rust constants don't since they're scoped.
=> post vm 0.18 migration cleanup

crates/miden-lib/build.rs
The build script was watching its own output directory (`{OUT_DIR}/assets`), creating a circular dependency that triggered recompilation on every cargo invocation.
We shouldn't need to recompile `miden-lib` if only modifying files downstream of `miden-lib`, like in `miden-testing`.
Example:
**Before**
```
touch crates/miden-testing/src/lib.rs 
cargo test --profile=test-dev --no-run
Compiling miden-lib v0.12.0 (/home/marti/dev/miden-base-main/crates/miden-lib)
Compiling miden-tx v0.12.0 (/home/marti/dev/miden-base-main/crates/miden-tx)
Compiling miden-block-prover v0.12.0 (/home/marti/dev/miden-base-main/crates/miden-block-prover)
Compiling miden-tx-batch-prover v0.12.0 (/home/marti/dev/miden-base-main/crates/miden-tx-batch-prover)
Compiling miden-testing v0.12.0 …
```
=> chore: remove circular check for generated files in `build.rs`
