objects/src/accounts/account_id.rs, objects/src/assets/mod.rs, objects/src/errors.rs, objects/src/lib.rs
This PR implements `Asset` and related objects.
One open questions: should we allow non-fungible assets to have amounts set to 0?
=> Implement Asset object

miden-lib/asm/sat/account.masm, miden-lib/asm/sat/asset.masm, miden-lib/asm/sat/constants.masm, miden-lib/asm/sat/epilogue.masm, miden-lib/asm/sat/layout.masm, miden-lib/asm/sat/tx.masm, miden-lib/src/lib.rs, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/common/procedures.rs, miden-lib/tests/test_account.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_note_setup.rs, miden-lib/tests/test_prologue.rs, miden-lib/tests/test_tx.rs, objects/src/accounts/code.rs, objects/src/notes/script.rs
This PR introduces the `create_note` procedure. This is a work in progress.
=> Introduce create note procedure

miden-lib/tests/common/data.rs, miden-lib/tests/test_account.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage.rs, objects/src/errors.rs, objects/src/lib.rs
This PR implements the changes required to support the update to the new `SimpleSmt` api.
=> chore: support simple smt api update

docs/src/introduction.md, docs/src/introduction/overview.md
I am reworking the intro and the overview—just small changes.
=> docs: changing intro and overview

miden-lib/asm/sat/layout.masm, miden-lib/src/memory.rs
This PR refactors the memory layout to provide more space for each section.
closes: #98
=> refactor memory layout

objects/src/accounts/code.rs, objects/src/errors.rs
=> typo fix: AccountCodeAsselmberError -> AccountCodeAssemblerError

miden-lib/Cargo.toml, miden-lib/src/memory.rs, miden-lib/tests/common/data.rs, miden-lib/tests/common/mod.rs, miden-lib/tests/common/procedures.rs, miden-lib/tests/test_epilogue.rs, miden-lib/tests/test_note.rs, miden-lib/tests/test_prologue.rs, miden-tx/Cargo.toml, objects/Cargo.toml, objects/src/accounts/mod.rs, objects/src/accounts/storage.rs
Review/Merge after https://github.com/0xPolygonMiden/miden-base/pull/154
The VM changed the API to receive u32 instead of u64 [ref](https://github.com/0xPolygonMiden/miden-vm/pull/933/files#diff-f02be9e480cda12fea6e1e68a47195f743fabdacd5f456e520cc59a56b174ecaL442). This updates the code accordingly.
=> Update address type

Cargo.toml, miden-lib/src/lib.rs, objects/src/accounts/code.rs, objects/src/accounts/storage.rs, objects/src/advice.rs, objects/src/block/header.rs, objects/src/block/mod.rs, objects/src/lib.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/transaction/consumed_notes.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/tx_witness.rs, objects/src/transaction/utils.rs
=> chore: enable resolver 2

miden-lib/asm/sat/internal/note.masm, miden-lib/asm/sat/kernel.masm, miden-lib/asm/sat/note.masm, miden-lib/tests/test_note.rs
=> Refactor note::get_assets kernel procedure

miden-lib/asm/sat/internal/layout.masm, miden-lib/src/memory.rs, miden-lib/tests/test_prologue.rs, objects/src/block/header.rs, objects/src/mock.rs
=> Add version and timestamp to block header

objects/src/accounts/account_id.rs, objects/src/accounts/mod.rs, objects/src/accounts/vault.rs, objects/src/assets/mod.rs, objects/src/lib.rs
=> Update rust `AssetVault`

objects/src/assets/mod.rs, objects/src/block/header.rs, objects/src/chain/mod.rs, objects/src/notes/envelope.rs, objects/src/notes/inputs.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/notes/origin.rs, objects/src/notes/script.rs, objects/src/notes/stub.rs, objects/src/notes/vault.rs
As the title says. This PR is pretty straightforward.
I noticed that the serde is missing validation to the `AccountId`, I will introduce that in another PR. Also, this is not doing transaction because that is a bit more complicated (also keeps this PR small)
=> Serde support for asset, block, and notes

objects/Cargo.toml, objects/src/builder/mod.rs, objects/src/lib.rs
~Review merge after: #205 / #204~
This adds builder for multiple structs, this allows one to construct mock data.
=> Account builder

objects/src/builder/mod.rs
This addresses @frisitano and @bobbinth  comments on https://github.com/0xPolygonMiden/miden-base/pull/206.
The idea is to make sure the `AccountId`'s is consistent with `storage_root` and `code_root`.
=> builder: ensure code and storage root are consistent

objects/Cargo.toml, objects/src/accounts/account_id.rs, objects/src/assets/nonfungible.rs, objects/src/builder/mod.rs, objects/src/mock/chain.rs
Opening the PR to expose the design and get feedback.
=> state: initial draft of a mock chain state

objects/Cargo.toml, objects/src/accounts/account_id.rs
Give some visual feedback via logging when doing the pow for a new account id
=> objects: add logging to track the status of an account PoW

objects/src/accounts/account_id.rs, objects/src/errors.rs
As per the PR title, this adds details to the error struct to aid debugging.
=> debug: added details for accountid pow validation

objects/src/accounts/seed.rs
While running the mock generation I noticed the threads didn't stop after the `OnceLock` was set. I wrote a small test program:
<details>
<summary>Example 1</summary>
```rust
use std::sync;
use std::thread;
use std::time::Duration;
fn t(once: sync::OnceLock<bool>) {
loop {
thread::sleep(Duration::from_secs(1));
if once.get().is_some() {
return;
}
println!("not set {:?}", once.get());
}
}
fn main() {
let once = sync::OnceLock::new();
let mut handles = Vec::new();
for _ in 0..8 {
let once = once.clone();
handles.push(thread::spawn(move || t(once)));
}
once.set(true).unwrap();
println!("set");
for h in handles {
h.join().unwrap();
}
}
```
</details>
And realized that `OnceLock::clone` doesn't behave like `Arc::clone`, meaning that this is not useful as a synchronization for the code on …
=> bugfix: cloning a OnceLock returns a new instance

Cargo.toml, miden-lib/Cargo.toml, miden-lib/tests/common/mod.rs, miden-tx/Cargo.toml, miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/executor/mod.rs, miden-tx/src/lib.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests.rs, miden-tx/src/verifier/mod.rs, objects/Cargo.toml, objects/src/lib.rs, objects/src/mock/account.rs, objects/src/mock/chain.rs, objects/src/mock/constants.rs, objects/src/mock/notes.rs, objects/src/mock/transaction.rs, objects/src/mock/utils.rs, objects/src/notes/envelope.rs, objects/src/transaction/created_notes.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/mod.rs, objects/src/transaction/tx_result.rs, objects/src/transaction/utils.rs
As requested on https://github.com/0xPolygonMiden/miden-base/issues/250
=> chore: unified processor/core dependencies

.editorconfig
=> config: add .editorconfig

objects/src/transaction/proven_tx.rs
=> derive `Clone` and `Debug` for `ProvenTransaction`

miden-lib/src/tests/mod.rs, miden-lib/src/tests/test_epilogue.rs, miden-lib/src/tests/test_prologue.rs, miden-tx/src/compiler/mod.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/error.rs, miden-tx/src/executor/mod.rs, miden-tx/src/lib.rs, miden-tx/src/prover/mod.rs, miden-tx/src/tests.rs, miden-tx/tests/test_miden_faucet_contract.rs, miden-tx/tests/test_miden_note_scripts.rs, miden-tx/tests/test_miden_wallet.rs, mock/src/lib.rs, objects/src/errors.rs, objects/src/lib.rs, objects/src/transaction/executed_tx.rs, objects/src/transaction/mod.rs, objects/src/transaction/prepared_tx.rs, objects/src/transaction/script.rs, objects/src/transaction/utils.rs
This is a draft PR that introduces the `TransactionScript` object.  It addresses issues described in #300.  This is not production ready, it still need to be cleaned up with proper error handling etc but before I continue any further I would like to discuss if the general approach is acceptable.
closes: #300
=> Introduce TransactionScript object

objects/src/lib.rs
=> Re-exporting `AstSerdeOptions`

miden-tx/src/host/event/vault_delta.rs, objects/src/accounts/account_id.rs, objects/src/assets/fungible.rs, objects/src/assets/nonfungible.rs
=> Make `AccountId::new_unchecked()` safe

docs/src/architecture/assets.md
Tiny changes on the asset chapter. I actually like it the way it is. Let me know what you want to have clearer.
=> Docs: iterating over assets chapter

docs/src/architecture/notes.md, docs/src/architecture/transactions.md
=> docs: fix note images

objects/src/transaction/script.rs
This PR adds `from_parts()` constructor to `TransactionScript` which makes instantiation of transaction scripts from known components (e.g., from database) easier.
=> Add `from_parts()` constructor to `TransactionScript`

miden-lib/Cargo.toml
Specifically useful for generating account IDs concurrently
=> Add `concurrent` feature to `miden-lib`

objects/src/accounts/mod.rs
This PR implements `Serializable` and `Deserializable` traits on the Account` struct.
=> Implement Serializable and Deserializable on Account

docs/src/architecture/accounts.md, docs/src/architecture/assets.md, docs/src/architecture/notes.md, docs/src/architecture/state.md, docs/src/architecture/transactions.md
- Contains few doc improvements
=> chore: doc improvements

objects/src/transaction/inputs.rs, objects/src/transaction/outputs.rs, objects/src/transaction/proven_tx.rs
=> Make `ProvenTransaction` `Sync`

miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/inputs.rs, miden-tx/tests/faucet_contract_test.rs, mock/src/builders/account.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage/mod.rs, objects/src/errors.rs
This PR implements `Account::apply_delta()` method which enabled application of `AccountDelta` object to an account.
=> Implement `apply_delta()` on `Account`

docs/src/architecture/accounts.md
These are small updates for the Account chapter. I tried to explain a bit more on how everything works. I added a subchapter about account code and described our basic wallet and basic fungible faucet account code and their respective interfaces. 
Please check first, if technically correct. Then language and flow.
=> Small updates on the account chapter

docs/src/architecture/accounts.md
=> docs: small fix in account chapter

mock/src/mock/chain.rs, objects/src/transaction/chain_mmr.rs
update the code to match the new api: https://github.com/0xPolygonMiden/crypto/pull/263
=> crypto: PartialMmr api changes

.github/workflows/ci.yml, Cargo.toml, Makefile
Updated CI, makefile and added profile test-release
=> Updated CI, makefile and added profile test-release

miden-lib/asm/miden/kernels/tx/prologue.masm
also tries to improve the documentation a bit.
=> prologue: check existing account's nonce is non-zero

objects/src/constants.rs, objects/src/lib.rs
This is prep work for https://github.com/0xPolygonMiden/miden-node/issues/65
=> Add block and batch constants

objects/src/accounts/code.rs, objects/src/notes/assets.rs, objects/src/notes/inputs.rs, objects/src/transaction/proven_tx.rs
Removes `OnceCell` and hashes everything on instantiation to make `ProvenTransaction` `Sync` for the node.
=> Try fix: making `ProvenTransaction` sync

objects/src/accounts/code.rs
Removes unnecessary leftover comment after #489
=> fix: Remove comment

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/asset.masm, miden-lib/asm/miden/contracts/faucets/basic_fungible.masm, miden-lib/asm/miden/kernels/tx/account.masm, miden-lib/asm/miden/kernels/tx/asset.masm, miden-lib/asm/miden/kernels/tx/asset_vault.masm, miden-lib/asm/miden/kernels/tx/epilogue.masm, miden-lib/asm/miden/kernels/tx/faucet.masm, miden-lib/asm/miden/kernels/tx/note.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/kernels/tx/tx.masm, miden-lib/asm/miden/note.masm, miden-lib/asm/note_scripts/P2ID.masm, miden-lib/asm/note_scripts/P2IDR.masm, miden-lib/asm/note_scripts/SWAP.masm
As per the title.
This starts the error code counter at 2**31
=> masm: add error codes

miden-tx/README.md
=> miden-tx: add readme

objects/README.md
Expand the README with some highlevel overview and links to further documentation.
=> objects: expand the README

Cargo.toml, miden-lib/Cargo.toml, miden-tx/Cargo.toml, mock/Cargo.toml, objects/Cargo.toml
- Moved miden deps to the workspace `Cargo.toml`
- Added `version` to the dependencies that had only `path`
- Add missing metadata when needed
=> deps: prepare deps for release

mock/README.md
Add a very short readme in case @bobbinth decides to publish this to crates.io.
=> mock: add short readme

.pre-commit-config.yaml, docs/src/introduction/getting-started.md
The pre-commit hook checks have been failing for a while. This fixes it.
=> pre-commit: fix errors and run all hooks

mkdocs.yml
=> One tab in the toc was out ... which stopped the site rendering

CHANGELOG.md, objects/Cargo.toml
This PR adds CHANGELOG file and updates the version of `miden-objects` to `v0.1.1` in preparation for v0.1.1 release.
=> Add changelog and update version of `miden-objects`.

miden-lib/src/accounts/faucets/mod.rs, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/tests/test_account.rs, miden-tx/tests/integration/main.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/wallet/mod.rs, mock/src/mock/account.rs, objects/src/accounts/mod.rs, objects/src/accounts/storage/mod.rs
Fixes a typo and some small readability improvements
=> Small test improvements

Cargo.lock, Cargo.toml, miden-tx/src/error.rs, objects/src/errors.rs, objects/src/transaction/proven_tx.rs
=> Ensure all errors implement at least `Debug`, `Clone`, `PartialEq` and `Eq` traits

CHANGELOG.md, Cargo.lock, miden-lib/Cargo.toml, miden-tx/src/host/mod.rs, miden-tx/tests/integration/scripts/faucet.rs, objects/Cargo.toml, objects/src/notes/inputs.rs, objects/src/notes/note_type.rs, objects/src/transaction/outputs.rs, objects/src/transaction/tx_args.rs
This PR contains changes for the v0.2.1 release.
=> v0.2.1 release

miden-lib/asm/kernels/transaction/main.masm, miden-lib/asm/miden/kernels/tx/epilogue.masm, miden-lib/src/tests/test_epilogue.rs, miden-lib/src/transaction/mod.rs, miden-lib/src/transaction/outputs.rs, miden-tx/src/prover/mod.rs, miden-tx/src/verifier/mod.rs, objects/src/transaction/proven_tx.rs
=> remove tx_script output from kernel (issue #505)

docs/introduction/get-started/create-account-use-faucet.md
Change "In this second" to "In this "section"
=> Fix grammar: create-account-use-faucet.md

docs/introduction/get-started/create-account-use-faucet.md, docs/introduction/get-started/p2p-private.md, docs/introduction/get-started/p2p-public.md, docs/introduction/get-started/prerequisites.md, docs/introduction/welcome.md, mkdocs.yml
Some cleanups for the tutorial
=> Cleanups before internal testing

objects/src/block/mod.rs, objects/src/block/note_tree.rs, objects/src/errors.rs
Follow-up to the comment: https://github.com/0xPolygonMiden/miden-node/pull/328#discussion_r1580665979
=> Implemented `Block::build_note_tree`

CHANGELOG.md, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/inputs.rs, mock/src/mock/chain.rs, objects/src/block/header.rs, objects/src/transaction/chain_mmr.rs
Related to issue https://github.com/0xPolygonMiden/miden-node/issues/236
=> Changed type of `version` and `timestamp` fields to `u32`

docs/index.md, docs/introduction/get-started/create-account-use-faucet.md, docs/introduction/get-started/p2p-private.md, docs/introduction/get-started/p2p-public.md
updating docs for changes from https://github.com/0xPolygonMiden/miden-client/pull/281
=> docs: update examples for changes in #281 from miden-client

docs/architecture/accounts.md, docs/architecture/notes.md, docs/architecture/state.md
Broken anchor links and one incorrect identifier.
=> A few small fixes to docs

docs/architecture/assets.md, docs/architecture/overview.md, docs/architecture/transactions/kernel.md, docs/index.md, docs/introduction/get-started/create-account-use-faucet.md, docs/introduction/get-started/p2p-private.md
After review from our internal department. 
I also removed some whitespace in this PR. This should be the last PR we merge against `main`. From now on, we should only merge docs PRs against `next` together with the code changes.
=> After compliance review

CHANGELOG.md, bench-tx/src/utils.rs, miden-lib/src/tests/test_tx.rs, miden-tx/src/host/note_builder.rs, miden-tx/src/prover/mod.rs, miden-tx/tests/integration/main.rs, mock/src/mock/notes.rs, mock/src/mock/transaction.rs, mock/src/procedures.rs, objects/src/notes/metadata.rs, objects/src/notes/mod.rs, objects/src/transaction/outputs.rs, objects/src/transaction/proven_tx.rs
This resolves https://github.com/0xPolygonMiden/miden-base/issues/586 and https://github.com/0xPolygonMiden/miden-base/issues/496
=> implemented support for full private notes

Cargo.lock, objects/src/accounts/storage/map.rs
Closes https://github.com/0xPolygonMiden/miden-base/issues/612
=> Change serialization of storage maps

docs/introduction/get-started/create-account-use-faucet.md, docs/introduction/get-started/p2p-private.md, docs/introduction/get-started/p2p-public.md
Addresses doc changes and consequences of in https://github.com/0xPolygonMiden/miden-client/issues/314.
=> docs: Update for client 0.3

bench-tx/src/main.rs, miden-tx/src/host/mod.rs, miden-tx/src/host/tx_authenticator.rs, miden-tx/src/lib.rs, miden-tx/tests/integration/main.rs, objects/src/accounts/auth.rs, objects/src/accounts/data.rs, objects/src/accounts/mod.rs
For https://github.com/0xPolygonMiden/miden-node/issues/349
=> fix: Move `AuthSecretKey` and use it on `AccountAuth` 

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/kernels/tx/tx.masm, miden-lib/asm/miden/tx.masm, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/inputs.rs, miden-lib/src/transaction/memory.rs, miden-lib/src/transaction/mod.rs, miden-tx/src/host/tx_authenticator.rs, miden-tx/src/verifier/mod.rs, objects/src/assets/mod.rs, objects/src/transaction/inputs.rs, objects/src/transaction/proven_tx.rs, objects/src/transaction/transaction_id.rs
This shouldn't change behavior, I only updated the comments while reading the prologue kernel to implement https://github.com/0xPolygonMiden/miden-base/issues/600 .
=> Fixes issue 680

docs/architecture/accounts.md
Small change in the description of Storage Maps
=> docs: changing the StorageMap description

miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/kernels/transaction/main.masm, miden-lib/asm/miden/contracts/auth/basic.masm, miden-lib/asm/miden/kernels/tx/memory.masm, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/asm/miden/kernels/tx/tx.masm, miden-lib/asm/miden/tx.masm, miden-lib/src/accounts/wallets/mod.rs, miden-lib/src/tests/test_prologue.rs, miden-lib/src/transaction/memory.rs, miden-lib/src/transaction/mod.rs, miden-tx/src/error.rs
First stacked PR for https://github.com/0xPolygonMiden/miden-base/issues/353#issuecomment-2137765721
Updates the variable names and documentation to match the new scheme.
=> chore: renamed nullifier to note commitment

README.md
Fixes https://github.com/0xPolygonMiden/miden-base/issues/716
=> fix: fixing broken link in README

CHANGELOG.md, miden-lib/asm/miden/kernels/tx/prologue.masm, miden-lib/src/transaction/inputs.rs, miden-tx/src/compiler/tests.rs, miden-tx/src/testing/chain_data.rs, objects/src/testing/block.rs, objects/src/transaction/inputs.rs
implements https://github.com/0xPolygonMiden/miden-base/issues/353
=> Delegated inclusion proofs

CHANGELOG.md, miden-lib/asm/miden/contracts/faucets/basic_fungible.masm
Some fixes in the fungible faucet comments and adding #752 to the CHANGELOG
=> fix: comments in fungible faucet

CHANGELOG.md, miden-lib/asm/miden/tx.masm, miden-tx/src/kernel_tests/test_tx.rs
PR for generalizing the build_recipient_hash procedure.
https://github.com/0xPolygonMiden/miden-base/issues/706
=> feat: generalize build_recipient_hash procedure

CHANGELOG.md, miden-lib/asm/kernels/transaction/api.masm, miden-lib/asm/miden/kernels/tx/note.masm, miden-lib/asm/miden/note.masm, miden-tx/src/kernel_tests/test_note.rs
=> Getting a note's serial number

docs/introduction/get-started/p2p-private.md
Removing specific faucet ID, and directing users to "Miden faucet website".
=> Miden: Update p2p-private.md

Cargo.lock, bench-tx/src/main.rs, miden-tx/src/testing/tx_context.rs, miden-tx/src/tests/kernel_tests/test_account.rs, miden-tx/src/tests/kernel_tests/test_asset_vault.rs, miden-tx/src/tests/kernel_tests/test_epilogue.rs, miden-tx/src/tests/kernel_tests/test_faucet.rs, miden-tx/src/tests/kernel_tests/test_note.rs, miden-tx/src/tests/kernel_tests/test_prologue.rs, miden-tx/src/tests/kernel_tests/test_tx.rs, miden-tx/src/tests/mod.rs, miden-tx/tests/integration/scripts/faucet.rs, miden-tx/tests/integration/scripts/p2id.rs, objects/src/testing/account.rs, objects/src/testing/account_id.rs, objects/src/testing/storage.rs
=> test: Add test for executing transactions with new accounts

CHANGELOG.md, objects/src/notes/execution_hint.rs
Useful for conversions in the node code
=> feat: add conversion for `NoteExecutionHint`

miden-tx/src/testing/tx_context/mod.rs, miden-tx/tests/integration/scripts/p2id.rs, objects/src/transaction/proven_tx.rs
This is a copy of #835 with clean commit history.
=> test: Consume multiple notes

CHANGELOG.md, objects/src/transaction/chain_mmr.rs, objects/src/transaction/inputs.rs, objects/src/transaction/tx_args.rs, objects/src/transaction/tx_witness.rs
This is part of https://github.com/0xPolygonMiden/miden-base/issues/860
=> feat: de-serialization for `TransactionWitness`

miden-tx/build.rs
This PR fixes a small issue in the `miden-tx` build script. Specifically, filters out all but `.masm` files which collecting a set of kernel errors.
=> Fix build script

objects/src/accounts/account_id.rs
Non-breaking fix for `AccountId::new_with_type_and_mode` producing IDs with the number of 1 bits lower than `MIN_ACCOUNT_ONES`.
The goal with the entire function was to make it easy to understand since we're using it only for testing, so the fix for ensuring `MIN_ACCOUNT_ONES` is also simple in nature.
This came up in: https://github.com/0xPolygonMiden/miden-client/pull/578#discussion_r1830056835.
=> fix(objects): Fix `AccountId::new_with_type_and_mode`

docs/introduction/get-started/p2p-public.md
For storage mode, change 'on-chain' to 'public'
=> fix deprecated storage mode

docs/architecture/accounts.md, docs/architecture/notes.md, docs/index.md
In this PR I propose to update the `Notes` section of the Miden documentation:
- more explanative
- more approachable for new developers
- shortened
- simplified
- re-phrased
- updated structure
=> [Docs]: Update `Notes` section

docs/introduction/get-started/create-account-use-faucet.md
This is a continuation of: https://github.com/0xPolygonMiden/miden-client/pull/670
=> docs: remove client's testing feature in docs

.github/workflows/lint.yml, Makefile, bin/proving-service/build.rs, crates/miden-lib/build.rs, crates/miden-proving-service-client/build.rs
=> chore: update env var for building proving services proto

crates/miden-objects/src/account/account_id/account_type.rs, crates/miden-objects/src/account/account_id/storage_mode.rs, crates/miden-objects/src/account/delta/mod.rs, crates/miden-objects/src/account/storage/slot/mod.rs
Adds missing docs described in [this comment](https://github.com/0xPolygonMiden/miden-client/pull/683#discussion_r1928532317)
=> docs: Missing types

CHANGELOG.md, bin/proving-service/build.rs, bin/proving-service/proto/tx_prover.proto, bin/proving-service/src/generated/mod.rs, bin/proving-service/src/generated/tx_prover.rs, crates/miden-proving-service-client/build.rs, crates/miden-proving-service-client/proto/tx_prover.proto, crates/miden-proving-service-client/src/lib.rs, crates/miden-proving-service-client/src/tx_prover/generated/mod.rs, crates/miden-proving-service-client/src/tx_prover/generated/nostd/mod.rs, crates/miden-proving-service-client/src/tx_prover/generated/nostd/tx_prover.rs, crates/miden-proving-service-client/src/tx_prover/generated/std/mod.rs, crates/miden-proving-service-client/src/tx_prover/generated/std/tx_prover.rs, proto/tx_prover.proto
=> chore: rename api.proto file to tx_prover.proto

CHANGELOG.md, crates/miden-objects/src/account/file.rs, crates/miden-objects/src/note/file.rs
=> feat(miden-objects): Make NoteFile and AccountFile more consistent

crates/miden-objects/src/note/nullifier.rs
As per https://github.com/0xPolygonMiden/miden-node/pull/706#discussion_r1963081045.
I imagine there are other types as well but maybe they should be added on an adhoc basis.
=> feat: add `Nullifier::dummy`

.github/workflows/lint.yml
Pin cargo machete to a specific version. Same as #1181 but targetting main to unblock #1191.
=> Pin cargo machete to a specific version

crates/miden-objects/src/account/component/template/mod.rs, crates/miden-objects/src/account/component/template/storage/mod.rs, crates/miden-objects/src/account/component/template/storage/placeholder.rs, docs/architecture/component_templates.md
Ref: https://github.com/0xPolygonMiden/miden-base/pull/1205#discussion_r1990786200
=> refactor(templates): `tokensymbol` -> `token_symbol`

CHANGELOG.md, Cargo.lock, crates/miden-tx/src/auth/signatures/mod.rs
This is parallel to https://github.com/0xPolygonMiden/miden-vm/pull/1661
=> Update advice provided to Falcon signature verification

Cargo.lock, Cargo.toml, crates/miden-lib/asm/miden/contracts/auth/basic.masm, crates/miden-lib/src/transaction/errors.rs, crates/miden-lib/src/transaction/events.rs, crates/miden-tx/src/host/mod.rs
Accompanying PR to https://github.com/0xPolygonMiden/miden-vm/pull/1703
=> Fix falcon event

CHANGELOG.md, Cargo.lock, bin/proving-service/Cargo.toml, bin/proving-service/src/proxy/worker.rs
Fixes a bug where the version check in the proxy fails
=> fix: compare versions fix

.github/actions/build_package/action.yml, .github/workflows/package.yml, bin/proving-service/README.md, packaging/prover-proxy/miden-prover-proxy.service, packaging/prover-proxy/postinst, packaging/prover-proxy/postrm, packaging/prover/miden-prover.service, packaging/prover/postinst, packaging/prover/postrm
Needs to be merged to main to come up as a workflow.
=> chore: Add Debian packaging action and workflow

packaging/prover-proxy/miden-prover-proxy.service, packaging/prover/miden-prover.service
Will re-package v0.8.1 with these fixes in place.
=> chore: Fix Debian service files

Cargo.lock, bin/proving-service/Cargo.toml, bin/proving-service/src/proxy/worker.rs
=> chore: use semver instead of own parser

Cargo.lock, Cargo.toml
Bump vm crates to v0.15.
part of #1374
=> Bump vm crates to v0.15

crates/miden-lib/build.rs
Removes stale MASM files in build.rs.
This addresses a problem where the build would fail if the cache still had a stale version of the file in its OUT_DIR. Usually, when the `asm` directory changes, it should use an entirely new build directory so technically this shouldn't be an issue. I wasn't able to find the root cause of it, (adding the `:` in `cargo::rerun-if-changed` wasn't the magic fix either), so I added an explicit deletion step for the `asm` directory.
=> Remove stale MASM files in build.rs

CHANGELOG.md, Cargo.lock, bin/bench-prover/src/bench_functions.rs, crates/miden-testing/Cargo.toml, crates/miden-testing/src/kernel_tests/batch/proposed_batch.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_errors.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs, crates/miden-testing/src/kernel_tests/block/proven_block_error.rs, crates/miden-testing/src/kernel_tests/block/proven_block_success.rs, crates/miden-testing/src/kernel_tests/block/utils.rs, crates/miden-testing/src/kernel_tests/tx/test_account.rs, crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs, crates/miden-testing/src/kernel_tests/tx/test_fpi.rs, crates/miden-testing/src/kernel_tests/tx/test_note.rs, crates/miden-testing/src/kernel_tests/tx/test_prologue.rs, crates/miden-testing/src/kernel_tests/tx/test_tx.rs, crates/miden-testing/src/mock_chain/chain.rs, crates/miden-testing/src/tx_context/builder.rs, crates/miden-testing/tests/integration/scripts/faucet.rs, crates/miden-testing/tests/integration/scripts/p2id.rs, crates/miden-testing/tests/integration/scripts/p2ide.rs, crates/miden-testing/tests/integration/scripts/send_note.rs, crates/miden-testing/tests/integration/scripts/swap.rs
All relevant changes concentrated in `chain.rs`, other files contain mostly mechanical changes to account for the new return types.
=> feat(testing): Errors on `MockChain`

CONTRIBUTING.md, Makefile
=> chore: Add `make install-tools`

crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/asm/kernels/transaction/lib/tx.masm, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
=> Optimize use of lt/gt with u32lt/u32gt

crates/miden-lib/build.rs, crates/miden-lib/src/account/interface/mod.rs, crates/miden-lib/src/note/well_known_note.rs, crates/miden-objects/src/account/account_id/seed.rs, crates/miden-objects/src/account/component/template/mod.rs, crates/miden-objects/src/account/component/template/storage/entry_content.rs, crates/miden-objects/src/account/component/template/storage/mod.rs, crates/miden-objects/src/batch/input_output_note_tracker.rs, crates/miden-objects/src/block/partial_account_tree.rs, crates/miden-objects/src/note/assets.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_errors.rs, crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs, crates/miden-testing/src/kernel_tests/block/proven_block_success.rs, crates/miden-testing/tests/auth/rpo_falcon_procedure_acl.rs, crates/miden-testing/tests/scripts/p2ide.rs, crates/miden-testing/tests/scripts/send_note.rs, crates/miden-tx/src/host/tx_progress.rs
Fixes the lints from the newly released Rust 1.89.
=> fix: lints from Rust 1.89

CHANGELOG.md, crates/miden-lib/src/account/auth/mod.rs, crates/miden-lib/src/account/wallets/mod.rs, crates/miden-objects/src/errors.rs
=> feat: refactor AccountError::AssumptionViolated

crates/miden-lib/asm/kernels/transaction/lib/memory.masm, crates/miden-lib/src/transaction/memory.rs, crates/miden-lib/src/transaction/procedures/kernel_v0.rs
close #1692 
Remove `TX_VAULT_ROOT_PTR` memory pointer as well as the underlying `TX_VAULT_ROOT`
=> chore: remove TX_VAULT_ROOT_PTR

CHANGELOG.md, Cargo.lock, crates/miden-block-prover/Cargo.toml, crates/miden-lib/Cargo.toml, crates/miden-objects/Cargo.toml, crates/miden-testing/Cargo.toml, crates/miden-tx-batch-prover/Cargo.toml, crates/miden-tx/Cargo.toml
Pending a patch of miden-vm as described [here](https://github.com/0xMiden/miden-base/pull/1928#issuecomment-3359628945)
=> chore: patch release v0.11.5

crates/miden-lib/asm/account_components/rpo_falcon_512_acl.masm
caught this while finding references for https://github.com/0xMiden/miden-base/pull/1925#discussion_r2410272977
=> fix: order of stack comment after loading storage
